
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SharpPy.PegGenerator.Grammar;

namespace SharpPy.PegGenerator.CodeGenerator
{
    /// <summary>
    /// Generates C# tokenizer code from PEG grammar tokens
    /// CPython 3.12 compatible tokenizer generation
    /// </summary>
    public class CSharpTokenizerGenerator
    {
        private readonly List<TokenDefinition> _tokens;
        private readonly StringBuilder _output;
        private int _indentLevel;

        public CSharpTokenizerGenerator(List<TokenDefinition> tokens)
        {
            _tokens = tokens;
            _output = new StringBuilder();
            _indentLevel = 0;
        }

        /// <summary>
        /// Generate the complete C# tokenizer class
        /// </summary>
        public string GenerateTokenizer()
        {
            GenerateHeader();
            GenerateTokenizerClass();
            return _output.ToString();
        }

        private void GenerateHeader()
        {
            WriteLine("// Generated tokenizer from Grammar/Tokens");
            WriteLine("// DO NOT EDIT - This file is automatically generated");
            WriteLine("// CPython 3.12 compatible tokenizer");
            WriteLine();
            WriteLine("using System;");
            WriteLine("using System.Collections.Generic;");
            WriteLine("using System.Linq;");
            WriteLine("using System.Text;");
            WriteLine("using System.Text.RegularExpressions;");
            WriteLine();
        }

        private void GenerateTokenizerClass()
        {
            WriteLine("namespace SharpPy.Generated");
            WriteLine("{");
            Indent();

            GenerateTokenTypeEnum(); // Generate enum from Grammar/Tokens
            GenerateTokenInfoClass();
            GenerateGeneratedTokenizerClass();

            Dedent();
            WriteLine("}"); // Close namespace
        }

        private void GenerateTokenTypeEnum()
        {
            WriteLine("/// <summary>");
            WriteLine("/// CPython 3.12 compatible token types");
            WriteLine("/// </summary>");
            WriteLine("public enum GeneratedTokenType");
            WriteLine("{");
            Indent();

            foreach (var token in _tokens)
            {
                WriteLine($"{token.Name},");
            }

            Dedent();
            WriteLine("}");
            WriteLine();
        }

        private void GenerateTokenInfoClass()
        {
            WriteLine("/// <summary>");
            WriteLine("/// CPython 3.12 compatible token info");
            WriteLine("/// </summary>");
            WriteLine("public class GeneratedTokenInfo");
            WriteLine("{");
            Indent();

            WriteLine("public GeneratedTokenType Type { get; set; }");
            WriteLine("public string Value { get; set; } = \"\";");
            WriteLine("public int Line { get; set; }");
            WriteLine("public int Column { get; set; }");
            WriteLine("public int Start { get; set; }");
            WriteLine("public int End { get; set; }");
            WriteLine();

            WriteLine("public GeneratedTokenInfo(GeneratedTokenType type, string value, int line, int column, int start = 0, int end = 0)");
            WriteLine("{");
            Indent();
            WriteLine("Type = type;");
            WriteLine("Value = value;");
            WriteLine("Line = line;");
            WriteLine("Column = column;");
            WriteLine("Start = start;");
            WriteLine("End = end;");
            Dedent();
            WriteLine("}");

            Dedent();
            WriteLine("}");
            WriteLine();
        }

        private void GenerateGeneratedTokenizerClass()
        {
            WriteLine("/// <summary>");
            WriteLine("/// Generated tokenizer for Python 3.12 grammar");
            WriteLine("/// </summary>");
            WriteLine("public class GeneratedPyTokenizer");
            WriteLine("{");
            Indent();

            GenerateTokenizerFields();
            GenerateTokenizerConstructor();
            GenerateTokenizerMethods();

            Dedent();
            WriteLine("}");
        }

        private void GenerateTokenizerFields()
        {
            WriteLine("private readonly string _source;");
            WriteLine("private readonly string _filename;");
            WriteLine("private int _position;");
            WriteLine("private int _line = 1;");
            WriteLine("private int _column = 0; // CPython uses 0-based column indexing");
            WriteLine("private readonly List<GeneratedTokenInfo> _tokens = new();");
            WriteLine();
            WriteLine("// INDENT/DEDENT handling");
            WriteLine("private readonly Stack<int> _indentStack = new();");
            WriteLine("private bool _atLineStart = true;");
            WriteLine("private readonly Queue<GeneratedTokenInfo> _pendingTokens = new();");
            WriteLine();

            // Generate keyword map for Python 3.12 keywords
            WriteLine("private static readonly Dictionary<string, GeneratedTokenType> Keywords = new()");
            WriteLine("{");
            Indent();

            // Python 3.12 keywords
            var pythonKeywords = new[]
            {
                "False", "None", "True", "__peg_parser__", "and", "as", "assert", "async", "await",
                "break", "class", "continue", "def", "del", "elif", "else", "except", "finally",
                "for", "from", "global", "if", "import", "in", "is", "lambda", "nonlocal", "not",
                "or", "pass", "raise", "return", "try", "while", "with", "yield", "match", "case"
            };

            foreach (var keyword in pythonKeywords)
            {
                WriteLine($"{{ \"{keyword}\", GeneratedTokenType.NAME }}, // {keyword}");
            }

            Dedent();
            WriteLine("};");
            WriteLine();

            // Generate operator map
            var operators = _tokens.Where(t => t.IsLiteral).ToList();
            if (operators.Any())
            {
                WriteLine("private static readonly Dictionary<string, GeneratedTokenType> Operators = new()");
                WriteLine("{");
                Indent();

                // Sort by length (longer first) to match properly
                var sortedOperators = operators.OrderByDescending(op => op.Value.Length);
                foreach (var op in sortedOperators)
                {
                    WriteLine($"{{ \"{EscapeString(op.Value)}\", GeneratedTokenType.{op.Name} }},");
                }

                Dedent();
                WriteLine("};");
                WriteLine();
            }
        }

        private void GenerateTokenizerConstructor()
        {
            WriteLine("public GeneratedPyTokenizer(string source, string filename = \"<string>\")");
            WriteLine("{");
            Indent();
            WriteLine("_source = source ?? throw new ArgumentNullException(nameof(source));");
            WriteLine("_filename = filename;");
            WriteLine("_position = 0;");
            WriteLine("_indentStack.Push(0); // Initialize with base indentation level");
            Dedent();
            WriteLine("}");
            WriteLine();
        }

        private void GenerateTokenizerMethods()
        {
            GenerateTokenizeMethod();
            GenerateHelperMethods();
        }

        private void GenerateTokenizeMethod()
        {
            WriteLine("/// <summary>");
            WriteLine("/// Tokenize the source code");
            WriteLine("/// </summary>");
            WriteLine("public List<GeneratedTokenInfo> Tokenize()");
            WriteLine("{");
            Indent();

            WriteLine("_tokens.Clear();");
            WriteLine("_position = 0;");
            WriteLine("_line = 1;");
            WriteLine("_column = 0; // CPython uses 0-based column indexing");
            WriteLine();

            WriteLine("while (_position < _source.Length)");
            WriteLine("{");
            Indent();

            WriteLine("// Handle indentation at line start");
            WriteLine("if (_atLineStart)");
            WriteLine("{");
            Indent();
            WriteLine("HandleIndentation();");
            Dedent();
            WriteLine("}");
            WriteLine();

            WriteLine("if (char.IsWhiteSpace(CurrentChar))");
            WriteLine("{");
            Indent();
            WriteLine("Console.WriteLine(\"[DEBUG] Whitespace found: '\");");
            WriteLine("// Skip whitespace handling if we're at line start");
            WriteLine("// (HandleIndentation already processed leading whitespace)");
            WriteLine("if (!_atLineStart)");
            WriteLine("{");
            Indent();
            WriteLine("HandleWhitespace();");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("// Handle only non-space whitespace at line start");
            WriteLine("if (CurrentChar == '\\n')");
            WriteLine("{");
            Indent();
            WriteLine("AddToken(GeneratedTokenType.NEWLINE, \"\\n\", _line, _column);");
            WriteLine("_atLineStart = true;");
            Dedent();
            WriteLine("}");
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine("else if (CurrentChar == '#')");
            WriteLine("{");
            Indent();
            WriteLine("HandleComment();");
            Dedent();
            WriteLine("}");
            WriteLine("else if (char.IsLetter(CurrentChar) || CurrentChar == '_')");
            WriteLine("{");
            Indent();
            WriteLine("HandleNameOrKeyword();");
            Dedent();
            WriteLine("}");
            WriteLine("else if (char.IsDigit(CurrentChar))");
            WriteLine("{");
            Indent();
            WriteLine("HandleNumber();");
            Dedent();
            WriteLine("}");
            WriteLine("else if (CurrentChar == '\\\"' || CurrentChar == '\\'')");
            WriteLine("{");
            Indent();
            WriteLine("HandleString();");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("if (!HandleOperator())");
            WriteLine("{");
            Indent();
            WriteLine("AddToken(GeneratedTokenType.ERRORTOKEN, CurrentChar.ToString(), _line, _column);");
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");

            Dedent();
            WriteLine("}");
            WriteLine();

            WriteLine("// Generate remaining DEDENT tokens at EOF");
            WriteLine("while (_indentStack.Count > 1)");
            WriteLine("{");
            Indent();
            WriteLine("_indentStack.Pop();");
            WriteLine("AddToken(GeneratedTokenType.DEDENT, \"\", _line, 0);");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Add ENDMARKER token");
            WriteLine("AddToken(GeneratedTokenType.ENDMARKER, \"\", _line, _column);");
            WriteLine("return _tokens;");

            Dedent();
            WriteLine("}");
            WriteLine();
        }

        private void GenerateHelperMethods()
        {
            // Current character property
            WriteLine("private char CurrentChar => _position < _source.Length ? _source[_position] : '\\0';");
            WriteLine();

            // Advance method
            WriteLine("private void Advance()");
            WriteLine("{");
            Indent();
            WriteLine("if (_position < _source.Length)");
            WriteLine("{");
            Indent();
            WriteLine("if (_source[_position] == '\\n')");
            WriteLine("{");
            Indent();
            WriteLine("_line++;");
            WriteLine("_column = 0; // CPython uses 0-based column indexing");
            WriteLine("_atLineStart = true; // Next position will be start of new line");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("_column++;");
            Dedent();
            WriteLine("}");
            WriteLine("_position++;");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Add token method
            WriteLine("private void AddToken(GeneratedTokenType type, string value)");
            WriteLine("{");
            Indent();
            WriteLine("_tokens.Add(new GeneratedTokenInfo(type, value, _line, _column));");
            Dedent();
            WriteLine("}");
            WriteLine();

            WriteLine("private void AddToken(GeneratedTokenType type, string value, int startLine, int startColumn)");
            WriteLine("{");
            Indent();
            WriteLine("_tokens.Add(new GeneratedTokenInfo(type, value, startLine, startColumn));");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Handle whitespace
            WriteLine("private void HandleWhitespace()");
            WriteLine("{");
            Indent();
            WriteLine("while (_position < _source.Length && char.IsWhiteSpace(CurrentChar))");
            WriteLine("{");
            Indent();
            WriteLine("if (CurrentChar == '\\n')");
            WriteLine("{");
            Indent();
            WriteLine("AddToken(GeneratedTokenType.NEWLINE, \"\\n\", _line, _column);");
            WriteLine("_atLineStart = true; // Next position will be start of new line");
            WriteLine("Advance();");
            WriteLine("break; // Stop processing whitespace after newline to let HandleIndentation process indentation");
            Dedent();
            WriteLine("}");
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Handle comment
            WriteLine("private void HandleComment()");
            WriteLine("{");
            Indent();
            WriteLine("var start = _position;");
            WriteLine("var startLine = _line;");
            WriteLine("var startColumn = _column;");
            WriteLine("while (_position < _source.Length && CurrentChar != '\\n')");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine("var comment = _source.Substring(start, _position - start);");
            WriteLine("AddToken(GeneratedTokenType.COMMENT, comment, startLine, startColumn);");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Handle name or keyword
            WriteLine("private void HandleNameOrKeyword()");
            WriteLine("{");
            Indent();
            WriteLine("var start = _position;");
            WriteLine("var startLine = _line;");
            WriteLine("var startColumn = _column;");
            WriteLine("while (_position < _source.Length && (char.IsLetterOrDigit(CurrentChar) || CurrentChar == '_'))");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine("var name = _source.Substring(start, _position - start);");
            WriteLine("var tokenType = Keywords.ContainsKey(name) ? Keywords[name] : GeneratedTokenType.NAME;");
            WriteLine("AddToken(tokenType, name, startLine, startColumn);");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Handle number
            WriteLine("private void HandleNumber()");
            WriteLine("{");
            Indent();
            WriteLine("var start = _position;");
            WriteLine("var startLine = _line;");
            WriteLine("var startColumn = _column;");
            WriteLine("while (_position < _source.Length && (char.IsDigit(CurrentChar) || CurrentChar == '.'))");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine("var number = _source.Substring(start, _position - start);");
            WriteLine("AddToken(GeneratedTokenType.NUMBER, number, startLine, startColumn);");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Handle string
            WriteLine("private void HandleString()");
            WriteLine("{");
            Indent();
            WriteLine("var quote = CurrentChar;");
            WriteLine("var start = _position;");
            WriteLine("var startLine = _line;");
            WriteLine("var startColumn = _column;");
            WriteLine("Advance(); // Skip opening quote");
            WriteLine();
            WriteLine("while (_position < _source.Length && CurrentChar != quote)");
            WriteLine("{");
            Indent();
            WriteLine("if (CurrentChar == '\\\\' && _position + 1 < _source.Length)");
            WriteLine("{");
            Indent();
            WriteLine("Advance(); // Skip escape character");
            Dedent();
            WriteLine("}");
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("if (_position < _source.Length)");
            WriteLine("{");
            Indent();
            WriteLine("Advance(); // Skip closing quote");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("var str = _source.Substring(start, _position - start);");
            WriteLine("AddToken(GeneratedTokenType.STRING, str, startLine, startColumn);");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Handle operator
            WriteLine("private bool HandleOperator()");
            WriteLine("{");
            Indent();
            WriteLine("var startLine = _line;");
            WriteLine("var startColumn = _column;");
            WriteLine("// Try to match operators from longest to shortest");
            WriteLine("foreach (var (op, tokenType) in Operators)");
            WriteLine("{");
            Indent();
            WriteLine("if (_position + op.Length <= _source.Length && _source.Substring(_position, op.Length) == op)");
            WriteLine("{");
            Indent();
            WriteLine("AddToken(tokenType, op, startLine, startColumn);");
            WriteLine("for (int i = 0; i < op.Length; i++) Advance();");
            WriteLine("return true;");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine("return false;");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Handle indentation for INDENT/DEDENT tokens
            WriteLine("private void HandleIndentation()");
            WriteLine("{");
            Indent();
            WriteLine("if (!_atLineStart) return;");
            WriteLine();
            WriteLine("Console.WriteLine(\"DEBUG: HandleIndentation called, atLineStart=\" + _atLineStart + \", line=\" + _line + \", col=\" + _column);");
            WriteLine("// Calculate current line indentation");
            WriteLine("int indent = 0;");
            WriteLine("while (_position < _source.Length && (CurrentChar == ' ' || CurrentChar == '\\t'))");
            WriteLine("{");
            Indent();
            WriteLine("indent += (CurrentChar == '\\t' ? 8 : 1);");
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("Console.WriteLine(\"DEBUG: Calculated indent=\" + indent + \", currentChar='\" + CurrentChar + \"'\");");
            WriteLine("// Skip empty lines and comment lines");
            WriteLine("if (_position >= _source.Length || CurrentChar == '\\n' || CurrentChar == '#')");
            WriteLine("{");
            Indent();
            WriteLine("Console.WriteLine(\"DEBUG: Skipping empty line or comment\");");
            WriteLine("return;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Handle indentation changes");
            WriteLine("int currentLevel = _indentStack.Peek();");
            WriteLine("Console.WriteLine(\"DEBUG: indent=\" + indent + \", currentLevel=\" + currentLevel);");
            WriteLine("if (indent > currentLevel)");
            WriteLine("{");
            Indent();
            WriteLine("// Increased indentation - INDENT");
            WriteLine("_indentStack.Push(indent);");
            WriteLine("var indentText = new string(' ', indent);");
            WriteLine("Console.WriteLine(\"DEBUG: Generated INDENT\");");
            WriteLine("AddToken(GeneratedTokenType.INDENT, indentText, _line, 0);");
            Dedent();
            WriteLine("}");
            WriteLine("else if (indent < currentLevel)");
            WriteLine("{");
            Indent();
            WriteLine("// Decreased indentation - DEDENT(s)");
            WriteLine("while (_indentStack.Count > 1 && _indentStack.Peek() > indent)");
            WriteLine("{");
            Indent();
            WriteLine("int dedentLevel = _indentStack.Pop();");
            WriteLine("Console.WriteLine(\"DEBUG: Generated DEDENT\");");
            WriteLine("AddToken(GeneratedTokenType.DEDENT, \"\", _line, 0);");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Check for indentation error");
            WriteLine("if (_indentStack.Count > 0 && _indentStack.Peek() != indent)");
            WriteLine("{");
            Indent();
            WriteLine("throw new InvalidOperationException($\"IndentationError: unindent does not match any outer indentation level at line {_line}\");");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("_atLineStart = false;");
            Dedent();
            WriteLine("}");
        }

        private string EscapeString(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r").Replace("\t", "\\t");
        }

        // Output helper methods
        private void WriteLine(string line = "")
        {
            if (!string.IsNullOrEmpty(line))
            {
                _output.Append(new string(' ', _indentLevel * 4));
                _output.AppendLine(line);
            }
            else
            {
                _output.AppendLine();
            }
        }

        private void Indent() => _indentLevel++;
        private void Dedent() => _indentLevel--;
    }
}