using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SharpPy.PegGenerator.Grammar;

namespace SharpPy.PegGenerator.CodeGenerator
{
    /// <summary>
    /// Generates C# parser code from PEG grammar
    /// </summary>
    public class CSharpCodeGenerator
    {
        private readonly Grammar.Grammar _grammar;
        private readonly List<TokenDefinition> _tokens;
        private readonly StringBuilder _output;
        private int _indentLevel;
        private int _groupCounter;

        public CSharpCodeGenerator(Grammar.Grammar grammar, List<TokenDefinition> tokens)
        {
            _grammar = grammar;
            _tokens = tokens;
            _output = new StringBuilder();
            _indentLevel = 0;
        }

        /// <summary>
        /// Generate the complete C# parser class
        /// </summary>
        public string GenerateParser()
        {
            GenerateHeader();
            GenerateParserClass();
            return _output.ToString();
        }

        private void GenerateHeader()
        {
            WriteLine("// Generated parser from Grammar/python.gram");
            WriteLine("// DO NOT EDIT - This file is automatically generated");
            WriteLine();
            WriteLine("using System;");
            WriteLine("using System.Collections.Generic;");
            WriteLine("using System.Linq;");
            WriteLine("using SharpPy;");
            WriteLine();
        }

        // GenerateTokenEnum method removed - tokens now generated in tokenizer only

        private void GenerateParserClass()
        {
            WriteLine("namespace SharpPy.Generated");
            WriteLine("{");
            Indent();

            // Generate AST node type definitions first
            WriteLine("// Generated AST node types for CPython 3.12 compatibility");
            WriteLine("public abstract class GeneratedAstNode { }");
            WriteLine("public class GeneratedStmt : GeneratedAstNode");
            WriteLine("{");
            Indent();
            WriteLine("public string? StatementType { get; set; }");
            WriteLine("public object? Value { get; set; }");
            Dedent();
            WriteLine("}");
            WriteLine("public class GeneratedExpr : GeneratedAstNode { }");
            WriteLine("public class GeneratedModule : GeneratedAstNode");
            WriteLine("{");
            Indent();
            WriteLine("public GeneratedStmtSeq? Body { get; set; }");
            Dedent();
            WriteLine("}");
            WriteLine("public class GeneratedSeq : List<GeneratedAstNode> { }");
            WriteLine("public class GeneratedStmtSeq : List<GeneratedStmt> { }");
            WriteLine("public class GeneratedExprSeq : List<GeneratedExpr> { }");
            WriteLine("public class GeneratedIdentifierSeq : List<string> { }");
            WriteLine("public class GeneratedPyObject { }");
            WriteLine("// GeneratedToken type defined in tokenizer");
            WriteLine();

            WriteLine("/// <summary>");
            WriteLine("/// Generated PEG parser for Python 3.12 grammar");
            WriteLine("/// </summary>");
            WriteLine("public class GeneratedPyParser");
            WriteLine("{");
            Indent();

            GenerateParserFields();
            GenerateParserConstructor();
            GenerateParserMethods();

            Dedent();
            WriteLine("}");

            Dedent();
            WriteLine("}"); // Close namespace
        }

        private void GenerateParserFields()
        {
            WriteLine("private readonly List<GeneratedTokenInfo> _tokens;");
            WriteLine("private int _position;");
            WriteLine("private readonly Dictionary<(int, string), object?> _memoCache = new();");
            WriteLine("private readonly string _filename;");
            WriteLine();
        }

        private void GenerateParserConstructor()
        {
            WriteLine("public GeneratedPyParser(List<GeneratedTokenInfo> tokens, string filename = \"<string>\")");
            WriteLine("{");
            Indent();
            WriteLine("_tokens = tokens ?? throw new ArgumentNullException(nameof(tokens));");
            WriteLine("_filename = filename;");
            WriteLine("_position = 0;");
            Dedent();
            WriteLine("}");
            WriteLine();
        }

        private void GenerateParserMethods()
        {
            // Generate helper methods
            GenerateHelperMethods();

            // Generate methods for each rule
            foreach (var rule in _grammar.Rules)
            {
                GenerateRuleMethod(rule);
            }
        }

        private void GenerateHelperMethods()
        {
            WriteLine("// Helper methods");

            // Current token property
            WriteLine("private GeneratedTokenInfo? CurrentToken => _position < _tokens.Count ? _tokens[_position] : null;");
            WriteLine();

            // Advance method
            WriteLine("private void Advance()");
            WriteLine("{");
            Indent();
            WriteLine("if (_position < _tokens.Count) _position++;");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Expect method
            WriteLine("private bool Expect(string expected)");
            WriteLine("{");
            Indent();
            WriteLine("if (CurrentToken?.Type.ToString() == expected)");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            WriteLine("return true;");
            Dedent();
            WriteLine("}");
            WriteLine("return false;");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Expect keyword method
            WriteLine("private bool ExpectKeyword(string keyword)");
            WriteLine("{");
            Indent();
            WriteLine("if (CurrentToken?.Type.ToString() == \"NAME\" && CurrentToken?.Value == keyword)");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            WriteLine("return true;");
            Dedent();
            WriteLine("}");
            WriteLine("return false;");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Mark/Reset for backtracking
            WriteLine("private int Mark() => _position;");
            WriteLine();
            WriteLine("private void Reset(int mark) => _position = mark;");
            WriteLine();

            // Memoization methods
            WriteLine("private T? GetMemo<T>(string ruleName)");
            WriteLine("{");
            Indent();
            WriteLine("var key = (_position, ruleName);");
            WriteLine("return _memoCache.TryGetValue(key, out var value) ? (T?)value : default;");
            Dedent();
            WriteLine("}");
            WriteLine();

            WriteLine("private void SetMemo<T>(string ruleName, T? value)");
            WriteLine("{");
            Indent();
            WriteLine("var key = (_position, ruleName);");
            WriteLine("_memoCache[key] = value;");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Add ParseZeroOrMore helper method
            WriteLine("private List<T> ParseZeroOrMore<T>(Func<T?> parseFunc) where T : class");
            WriteLine("{");
            Indent();
            WriteLine("var results = new List<T>();");
            WriteLine("while (true)");
            WriteLine("{");
            Indent();
            WriteLine("var startPos = _position;");
            WriteLine("var result = parseFunc();");
            WriteLine("if (result == null)");
            WriteLine("{");
            Indent();
            WriteLine("_position = startPos;");
            WriteLine("break;");
            Dedent();
            WriteLine("}");
            WriteLine("results.Add(result);");
            Dedent();
            WriteLine("}");
            WriteLine("return results;");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Add ParseOneOrMore helper method
            WriteLine("private List<T>? ParseOneOrMore<T>(Func<T?> parseFunc) where T : class");
            WriteLine("{");
            Indent();
            WriteLine("var results = ParseZeroOrMore(parseFunc);");
            WriteLine("return results.Count > 0 ? results : null;");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Add ParseOptional helper method
            WriteLine("private T? ParseOptional<T>(Func<T?> parseFunc) where T : class");
            WriteLine("{");
            Indent();
            WriteLine("var startPos = _position;");
            WriteLine("var result = parseFunc();");
            WriteLine("if (result == null)");
            WriteLine("{");
            Indent();
            WriteLine("_position = startPos;");
            Dedent();
            WriteLine("}");
            WriteLine("return result;");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Add ParseGroup helper method
            WriteLine("private T? ParseGroup<T>(Func<T?> parseFunc) where T : class");
            WriteLine("{");
            Indent();
            WriteLine("return parseFunc();");
            Dedent();
            WriteLine("}");
            WriteLine();

        }

        private void GenerateRuleMethod(Rule rule)
        {
            var returnType = TranslateCTypeToCS(rule.ReturnType ?? "object?");
            var methodName = ToCSharpMethodName(rule.Name);

            WriteLine($"// Rule: {rule.Name}");
            WriteLine($"public {returnType} {methodName}()");
            WriteLine("{");
            Indent();

            // Phase 2: Start implementing specific rules
            if (rule.Name == "file")
            {
                GenerateFileMethod(returnType);
            }
            else if (rule.Name == "statements")
            {
                GenerateStatementsMethod(returnType);
            }
            else if (rule.Name == "statement")
            {
                GenerateStatementMethod(returnType);
            }
            else if (rule.Name == "simple_stmts")
            {
                GenerateSimpleStmtsMethod(returnType);
            }
            else if (rule.Name == "simple_stmt")
            {
                GenerateSimpleStmtMethod(returnType);
            }
            else if (rule.Name == "atom")
            {
                GenerateAtomMethod(returnType);
            }
            else
            {
                WriteLine("// Phase 1: Minimal implementation");
                WriteLine($"return default({returnType});");
            }

            Dedent();
            WriteLine("}");
            WriteLine();
        }

        private void GenerateFileMethod(string returnType)
        {
            // file[mod_ty]: a=[statements] ENDMARKER { _PyPegen_make_module(p, a) }
            WriteLine("// file[mod_ty]: a=[statements] ENDMARKER { _PyPegen_make_module(p, a) }");
            WriteLine("var statements = Statements(); // Parse optional statements");
            WriteLine();
            WriteLine("if (!Expect(\"ENDMARKER\"))");
            WriteLine("{");
            Indent();
            WriteLine("// If no ENDMARKER, we're not at end of file - this is an error for complete parsing");
            WriteLine("// For now, continue gracefully");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Create a module containing the statements");
            WriteLine($"var module = new {returnType}();");
            WriteLine("module.Body = statements;");
            WriteLine("return module;");
        }

        private void GenerateStatementsMethod(string returnType)
        {
            // statements[asdl_stmt_seq*]: a=statement+ { (asdl_stmt_seq*)_PyPegen_seq_flatten(p, a) }
            WriteLine("// statements[asdl_stmt_seq*]: a=statement+ { (asdl_stmt_seq*)_PyPegen_seq_flatten(p, a) }");
            WriteLine("var statementList = new List<GeneratedStmt>();");
            WriteLine();
            WriteLine("// Parse one or more statements");
            WriteLine("while (_position < _tokens.Count && CurrentToken?.Type.ToString() != \"ENDMARKER\")");
            WriteLine("{");
            Indent();
            WriteLine("var stmtSeq = Statement(); // Returns GeneratedStmtSeq");
            WriteLine("if (stmtSeq != null && stmtSeq.Count > 0)");
            WriteLine("{");
            Indent();
            WriteLine("// Add all statements from the sequence");
            WriteLine("statementList.AddRange(stmtSeq);");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("// No more statements to parse");
            WriteLine("break;");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Convert to statement sequence");
            WriteLine($"var result = new {returnType}();");
            WriteLine("result.AddRange(statementList);");
            WriteLine("return result;");
        }

        private void GenerateSimpleStmtMethod(string returnType)
        {
            // simple_stmt[stmt_ty] with multiple alternatives including 'pass', 'break', 'continue'
            WriteLine("// simple_stmt[stmt_ty]: Multiple alternatives including simple keyword statements");
            WriteLine();
            WriteLine("// Try 'pass' keyword (simplest case)");
            WriteLine("if (ExpectKeyword(\"pass\"))");
            WriteLine("{");
            Indent();
            WriteLine("// 'pass' { _PyAST_Pass(EXTRA) }");
            WriteLine($"var passStmt = new {returnType}();");
            WriteLine("passStmt.StatementType = \"pass\";");
            WriteLine("return passStmt;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Try 'break' keyword");
            WriteLine("if (ExpectKeyword(\"break\"))");
            WriteLine("{");
            Indent();
            WriteLine("// 'break' { _PyAST_Break(EXTRA) }");
            WriteLine($"var breakStmt = new {returnType}();");
            WriteLine("breakStmt.StatementType = \"break\";");
            WriteLine("return breakStmt;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Try 'continue' keyword");
            WriteLine("if (ExpectKeyword(\"continue\"))");
            WriteLine("{");
            Indent();
            WriteLine("// 'continue' { _PyAST_Continue(EXTRA) }");
            WriteLine($"var continueStmt = new {returnType}();");
            WriteLine("continueStmt.StatementType = \"continue\";");
            WriteLine("return continueStmt;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Try assignment statement (name = expression)");
            WriteLine("var savedPos = _position;");
            WriteLine("var nameToken = CurrentToken;");
            WriteLine("if (nameToken != null && nameToken.Type == GeneratedTokenType.NAME)");
            WriteLine("{");
            Indent();
            WriteLine("Advance(); // consume name");
            WriteLine("if (CurrentToken?.Type == GeneratedTokenType.EQUAL)");
            WriteLine("{");
            Indent();
            WriteLine("Advance(); // consume '='");
            WriteLine("// For now, expect a NUMBER token for the value");
            WriteLine("var valueToken = CurrentToken;");
            WriteLine("if (valueToken?.Type == GeneratedTokenType.NUMBER)");
            WriteLine("{");
            Indent();
            WriteLine("Advance(); // consume number");
            WriteLine($"var assignStmt = new {returnType}();");
            WriteLine("assignStmt.StatementType = \"assignment\";");
            WriteLine("assignStmt.Value = new { Target = nameToken.Value, Value = valueToken.Value };");
            WriteLine("return assignStmt;");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine("_position = savedPos; // backtrack");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Try 'return' statement");
            WriteLine("if (ExpectKeyword(\"return\"))");
            WriteLine("{");
            Indent();
            WriteLine("// Check if there's a value after return");
            WriteLine("object? returnValue = null;");
            WriteLine("if (CurrentToken?.Type == GeneratedTokenType.NUMBER)");
            WriteLine("{");
            Indent();
            WriteLine("returnValue = CurrentToken.Value;");
            WriteLine("Advance(); // consume number");
            Dedent();
            WriteLine("}");
            WriteLine($"var returnStmt = new {returnType}();");
            WriteLine("returnStmt.StatementType = \"return\";");
            WriteLine("returnStmt.Value = returnValue;");
            WriteLine("return returnStmt;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Try simple expression statement (NUMBER)");
            WriteLine("if (CurrentToken?.Type == GeneratedTokenType.NUMBER)");
            WriteLine("{");
            Indent();
            WriteLine("var numberToken = CurrentToken;");
            WriteLine("Advance(); // consume number");
            WriteLine($"var exprStmt = new {returnType}();");
            WriteLine("exprStmt.StatementType = \"expression\";");
            WriteLine("exprStmt.Value = numberToken.Value;");
            WriteLine("return exprStmt;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// TODO: Add other simple statement alternatives");
            WriteLine("// - type_alias");
            WriteLine("// - star_expressions");
            WriteLine("// - return_stmt, import_stmt, raise_stmt, del_stmt, yield_stmt, assert_stmt");
            WriteLine("// - function calls, complex expressions");
            WriteLine();
            WriteLine("// No match found");
            WriteLine($"return default({returnType});");
        }

        private void GenerateAtomMethod(string returnType)
        {
            // atom[expr_ty]: NAME | 'True' | 'False' | 'None' | strings | NUMBER | ...
            WriteLine("// atom[expr_ty]: Basic expressions (NAME, NUMBER, True/False/None, STRING)");
            WriteLine();
            WriteLine("// Try NAME token (variable names)");
            WriteLine("if (CurrentToken?.Type.ToString() == \"NAME\")");
            WriteLine("{");
            Indent();
            WriteLine("var nameValue = CurrentToken.Value;");
            WriteLine("Advance();");
            WriteLine($"var nameExpr = new {returnType}();");
            WriteLine("// TODO: Set name expression properties when structure is defined");
            WriteLine("return nameExpr;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Try NUMBER token");
            WriteLine("if (CurrentToken?.Type.ToString() == \"NUMBER\")");
            WriteLine("{");
            Indent();
            WriteLine("var numberValue = CurrentToken.Value;");
            WriteLine("Advance();");
            WriteLine($"var numberExpr = new {returnType}();");
            WriteLine("// TODO: Set number expression properties when structure is defined");
            WriteLine("return numberExpr;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Try STRING token");
            WriteLine("if (CurrentToken?.Type.ToString() == \"STRING\")");
            WriteLine("{");
            Indent();
            WriteLine("var stringValue = CurrentToken.Value;");
            WriteLine("Advance();");
            WriteLine($"var stringExpr = new {returnType}();");
            WriteLine("// TODO: Set string expression properties when structure is defined");
            WriteLine("return stringExpr;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Try literal keywords");
            WriteLine("if (ExpectKeyword(\"True\"))");
            WriteLine("{");
            Indent();
            WriteLine("// 'True' { _PyAST_Constant(Py_True, NULL, EXTRA) }");
            WriteLine($"var trueExpr = new {returnType}();");
            WriteLine("// TODO: Set True constant properties when structure is defined");
            WriteLine("return trueExpr;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("if (ExpectKeyword(\"False\"))");
            WriteLine("{");
            Indent();
            WriteLine("// 'False' { _PyAST_Constant(Py_False, NULL, EXTRA) }");
            WriteLine($"var falseExpr = new {returnType}();");
            WriteLine("// TODO: Set False constant properties when structure is defined");
            WriteLine("return falseExpr;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("if (ExpectKeyword(\"None\"))");
            WriteLine("{");
            Indent();
            WriteLine("// 'None' { _PyAST_Constant(Py_None, NULL, EXTRA) }");
            WriteLine($"var noneExpr = new {returnType}();");
            WriteLine("// TODO: Set None constant properties when structure is defined");
            WriteLine("return noneExpr;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// TODO: Add other atom alternatives");
            WriteLine("// - strings (complex string handling)");
            WriteLine("// - tuple, list, dict literals");
            WriteLine("// - '...' (Ellipsis)");
            WriteLine();
            WriteLine("// No match found");
            WriteLine($"return default({returnType});");
        }

        private void GenerateStatementMethod(string returnType)
        {
            // statement[asdl_stmt_seq*]: a=compound_stmt { (asdl_stmt_seq*)_PyPegen_singleton_seq(p, a) } | simple_stmts
            WriteLine("// statement[asdl_stmt_seq*]: compound_stmt | simple_stmts");
            WriteLine();
            WriteLine("// Try simple_stmts first (easier to implement)");
            WriteLine("var simpleStmts = SimpleStmts();");
            WriteLine("if (simpleStmts != null)");
            WriteLine("{");
            Indent();
            WriteLine("return simpleStmts;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// TODO: Add compound_stmt support later");
            WriteLine("// - if_stmt, while_stmt, for_stmt, with_stmt, try_stmt, etc.");
            WriteLine();
            WriteLine("// No match found");
            WriteLine($"return default({returnType});");
        }

        private void GenerateSimpleStmtsMethod(string returnType)
        {
            // simple_stmts[asdl_stmt_seq*]: a=simple_stmt b=newline { (asdl_stmt_seq*)_PyPegen_singleton_seq(p, a) }
            WriteLine("// simple_stmts[asdl_stmt_seq*]: simple_stmt NEWLINE | simple_stmt $$");
            WriteLine();
            WriteLine("var stmt = SimpleStmt();");
            WriteLine("if (stmt != null)");
            WriteLine("{");
            Indent();
            WriteLine("// Skip optional newline");
            WriteLine("if (CurrentToken?.Type.ToString() == \"NEWLINE\")");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Create statement sequence with single statement");
            WriteLine($"var stmtSeq = new {returnType}();");
            WriteLine("stmtSeq.Add(stmt);");
            WriteLine("return stmtSeq;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// No statement found");
            WriteLine($"return default({returnType});");
        }

        private void GenerateAlternative(Alternative alt, string returnType, string ruleName)
        {
            // Phase 1: Minimal implementation - just return default
            WriteLine($"// Alternative implementation simplified for Phase 1");
            WriteLine($"return default({returnType});");
        }

        private string GenerateAtomCode(Atom atom)
        {
            // Phase 1: Minimal implementation - everything returns null for compilation
            return "null";
        }

        private bool IsToken(string name)
        {
            return _tokens.Any(t => t.Name == name);
        }

        private string ProcessAction(string action, Dictionary<string, string> variables)
        {
            // Simple variable substitution and C++ to C# conversion
            var result = action;

            // Replace variables
            foreach (var (name, varName) in variables)
            {
                result = result.Replace(name, varName);
            }

            // Convert C++ pointer access to C# property access
            result = result.Replace("->lineno", ".Line");
            result = result.Replace("->col_offset", ".Column");

            // Handle common CPython function calls
            result = result.Replace("RAISE_SYNTAX_ERROR", "throw new PySyntaxError");
            result = result.Replace("RAISE_INDENTATION_ERROR", "throw new PyIndentationError");

            return result;
        }

        private string ToCSharpMethodName(string grammarName)
        {
            // Convert grammar rule name to C# method name
            var parts = grammarName.Split('_');
            return string.Join("", parts.Select(p =>
                char.ToUpper(p[0]) + p.Substring(1).ToLower()));
        }

        private string TranslateCTypeToCS(string cType)
        {
            // Convert CPython C types to C# types - CPython 3.12 compatible
            return cType switch
            {
                "mod_ty" => "GeneratedModule", // Python module type
                "asdl_stmt_seq*" => "GeneratedStmtSeq", // Statement sequence
                "asdl_expr_seq*" => "GeneratedExprSeq", // Expression sequence
                "stmt_ty" => "GeneratedStmt", // Statement type
                "expr_ty" => "GeneratedExpr", // Expression type
                "asdl_seq*" => "GeneratedSeq", // Generic sequence
                "asdl_identifier_seq*" => "GeneratedIdentifierSeq", // Identifier sequence
                "string" => "string",
                "int" => "int",
                "void" => "object", // Changed: void cannot be used as generic type parameter in C#
                "PyObject*" => "GeneratedPyObject", // Python object
                "token*" => "GeneratedTokenInfo", // Token type
                _ when cType.EndsWith("_ty") => "GeneratedAstNode", // AST node types
                _ when cType.EndsWith("*") => "GeneratedSeq", // Generic pointer types
                _ => cType // Keep as-is for standard types
            };
        }


        // Output helper methods
        private void WriteLine(string line = "")
        {
            if (!string.IsNullOrEmpty(line))
            {
                _output.Append(new string(' ', _indentLevel * 4));
                _output.AppendLine(line);
            }
            else
            {
                _output.AppendLine();
            }
        }

        private void Indent() => _indentLevel++;
        private void Dedent() => _indentLevel--;

        private string EscapeForCSharp(string value)
        {
            // Remove outer quotes if present and escape for C#
            var cleanValue = value;
            if ((cleanValue.StartsWith("\"") && cleanValue.EndsWith("\"")) ||
                (cleanValue.StartsWith("'") && cleanValue.EndsWith("'")))
            {
                cleanValue = cleanValue.Substring(1, cleanValue.Length - 2);
            }
            return cleanValue.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private string SanitizeVariableName(string name)
        {
            // List of C# keywords to avoid
            var csharpKeywords = new HashSet<string>
            {
                "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
                "checked", "class", "const", "continue", "decimal", "default", "delegate",
                "do", "double", "else", "enum", "event", "explicit", "extern", "false",
                "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
                "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
                "new", "null", "object", "operator", "out", "override", "params", "private",
                "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
                "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
                "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
                "unsafe", "ushort", "using", "var", "virtual", "void", "volatile", "while"
            };

            return csharpKeywords.Contains(name) ? $"@{name}" : name;
        }
    }
}