using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SharpPy.PegGenerator.Grammar;

namespace SharpPy.PegGenerator.CodeGenerator
{
    /// <summary>
    /// Generates C# parser code from PEG grammar
    /// </summary>
    public class CSharpCodeGenerator
    {
        private readonly Grammar.Grammar _grammar;
        private readonly List<TokenDefinition> _tokens;
        private readonly StringBuilder _output;
        private int _indentLevel;
        private int _groupCounter;

        public CSharpCodeGenerator(Grammar.Grammar grammar, List<TokenDefinition> tokens)
        {
            _grammar = grammar;
            _tokens = tokens;
            _output = new StringBuilder();
            _indentLevel = 0;
        }

        /// <summary>
        /// Generate the complete C# parser class
        /// </summary>
        public string GenerateParser()
        {
            GenerateHeader();
            GenerateTokenEnum();
            GenerateParserClass();
            return _output.ToString();
        }

        private void GenerateHeader()
        {
            WriteLine("// Generated parser from Grammar/python.gram");
            WriteLine("// DO NOT EDIT - This file is automatically generated");
            WriteLine();
            WriteLine("using System;");
            WriteLine("using System.Collections.Generic;");
            WriteLine("using System.Linq;");
            WriteLine("using SharpPy;");
            WriteLine();
        }

        private void GenerateTokenEnum()
        {
            WriteLine("namespace SharpPy.Generated");
            WriteLine("{");
            Indent();

            WriteLine("public enum TokenType");
            WriteLine("{");
            Indent();

            foreach (var token in _tokens)
            {
                WriteLine($"{token.Name},");
            }

            Dedent();
            WriteLine("}");
            WriteLine();

            // Generate Token class
            WriteLine("public class Token");
            WriteLine("{");
            Indent();
            WriteLine("public string Type { get; set; } = \"\";");
            WriteLine("public string Value { get; set; } = \"\";");
            WriteLine("public int Line { get; set; }");
            WriteLine("public int Column { get; set; }");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Generate token literals map
            var literals = _tokens.Where(t => t.IsLiteral).ToList();
            if (literals.Any())
            {
                WriteLine("public static class TokenLiterals");
                WriteLine("{");
                Indent();

                WriteLine("public static readonly Dictionary<string, TokenType> Map = new()");
                WriteLine("{");
                Indent();

                foreach (var literal in literals)
                {
                    WriteLine($"{{ \"{literal.Value}\", TokenType.{literal.Name} }},");
                }

                Dedent();
                WriteLine("};");

                Dedent();
                WriteLine("}");
                WriteLine();
            }
        }

        private void GenerateParserClass()
        {
            WriteLine("/// <summary>");
            WriteLine("/// Generated PEG parser for Python 3.12 grammar");
            WriteLine("/// </summary>");
            WriteLine("public class GeneratedPyParser");
            WriteLine("{");
            Indent();

            GenerateParserFields();
            GenerateParserConstructor();
            GenerateParserMethods();

            Dedent();
            WriteLine("}");

            Dedent();
            WriteLine("}"); // Close namespace
        }

        private void GenerateParserFields()
        {
            WriteLine("private readonly List<Token> _tokens;");
            WriteLine("private int _position;");
            WriteLine("private readonly Dictionary<(int, string), object?> _memoCache = new();");
            WriteLine("private readonly string _filename;");
            WriteLine();
        }

        private void GenerateParserConstructor()
        {
            WriteLine("public GeneratedPyParser(List<Token> tokens, string filename = \"<string>\")");
            WriteLine("{");
            Indent();
            WriteLine("_tokens = tokens ?? throw new ArgumentNullException(nameof(tokens));");
            WriteLine("_filename = filename;");
            WriteLine("_position = 0;");
            Dedent();
            WriteLine("}");
            WriteLine();
        }

        private void GenerateParserMethods()
        {
            // Generate helper methods
            GenerateHelperMethods();

            // Generate methods for each rule
            foreach (var rule in _grammar.Rules)
            {
                GenerateRuleMethod(rule);
            }
        }

        private void GenerateHelperMethods()
        {
            WriteLine("// Helper methods");

            // Current token property
            WriteLine("private Token? CurrentToken => _position < _tokens.Count ? _tokens[_position] : null;");
            WriteLine();

            // Advance method
            WriteLine("private void Advance()");
            WriteLine("{");
            Indent();
            WriteLine("if (_position < _tokens.Count) _position++;");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Expect method
            WriteLine("private bool Expect(string expected)");
            WriteLine("{");
            Indent();
            WriteLine("if (CurrentToken?.Type == expected)");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            WriteLine("return true;");
            Dedent();
            WriteLine("}");
            WriteLine("return false;");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Expect keyword method
            WriteLine("private bool ExpectKeyword(string keyword)");
            WriteLine("{");
            Indent();
            WriteLine("if (CurrentToken?.Type == \"NAME\" && CurrentToken?.Value == keyword)");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            WriteLine("return true;");
            Dedent();
            WriteLine("}");
            WriteLine("return false;");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Mark/Reset for backtracking
            WriteLine("private int Mark() => _position;");
            WriteLine();
            WriteLine("private void Reset(int mark) => _position = mark;");
            WriteLine();

            // Memoization methods
            WriteLine("private T? GetMemo<T>(string ruleName)");
            WriteLine("{");
            Indent();
            WriteLine("var key = (_position, ruleName);");
            WriteLine("return _memoCache.TryGetValue(key, out var value) ? (T?)value : default;");
            Dedent();
            WriteLine("}");
            WriteLine();

            WriteLine("private void SetMemo<T>(string ruleName, T? value)");
            WriteLine("{");
            Indent();
            WriteLine("var key = (_position, ruleName);");
            WriteLine("_memoCache[key] = value;");
            Dedent();
            WriteLine("}");
            WriteLine();
        }

        private void GenerateRuleMethod(Rule rule)
        {
            var returnType = TranslateCTypeToCS(rule.ReturnType ?? "object?");
            var methodName = ToCSharpMethodName(rule.Name);

            WriteLine($"// Rule: {rule.Name}");
            WriteLine($"public {returnType} {methodName}()");
            WriteLine("{");
            Indent();

            // Memoization check
            if (rule.IsMemoized)
            {
                WriteLine($"var memo = GetMemo<{returnType}>(\"{rule.Name}\");");
                WriteLine("if (memo != null) return memo;");
                WriteLine();
                WriteLine("var startPos = _position;");
            }

            // Generate alternatives
            for (int i = 0; i < rule.Alternatives.Count; i++)
            {
                var alt = rule.Alternatives[i];

                if (i > 0)
                {
                    WriteLine("// Try next alternative");
                    WriteLine("Reset(startPos);");
                }

                WriteLine($"// Alternative {i + 1}");
                WriteLine("{");
                Indent();

                GenerateAlternative(alt, returnType);

                Dedent();
                WriteLine("}");
                WriteLine();
            }

            // If no alternative succeeded
            if (rule.IsMemoized)
            {
                WriteLine($"SetMemo(\"{rule.Name}\", default({returnType}));");
            }
            WriteLine($"return default({returnType});");

            Dedent();
            WriteLine("}");
            WriteLine();
        }

        private void GenerateAlternative(Alternative alt, string returnType)
        {
            var variables = new Dictionary<string, string>();
            var sequence = new List<string>();

            // Generate code for each item in the sequence
            for (int i = 0; i < alt.Items.Count; i++)
            {
                var item = alt.Items[i];
                var varName = item.Name ?? $"_item{i}";
                var atomCode = GenerateAtomCode(item.Atom);

                WriteLine($"var {varName} = {atomCode};");
                WriteLine($"if ({varName} == null) return default({returnType});");

                if (item.Name != null)
                {
                    variables[item.Name] = varName;
                }
                sequence.Add(varName);
            }

            // Generate action or default return
            if (!string.IsNullOrEmpty(alt.Action))
            {
                var action = ProcessAction(alt.Action, variables);
                WriteLine($"var result = {action};");
                WriteLine("SetMemo(\"{rule.Name}\", result);");
                WriteLine("return result;");
            }
            else if (sequence.Count == 1)
            {
                WriteLine($"return {sequence[0]};");
            }
            else
            {
                // Default: return the first non-null item or create a list
                WriteLine($"return {sequence[0]};");
            }
        }

        private string GenerateAtomCode(Atom atom)
        {
            return atom switch
            {
                RuleRef ruleRef => IsToken(ruleRef.Name)
                    ? $"Expect(\"{ruleRef.Name}\") ? CurrentToken : null"
                    : $"{ToCSharpMethodName(ruleRef.Name)}()",
                StringLiteral str => $"ExpectToken(\"{str.Value}\")",
                Optional opt => $"({GenerateAtomCode(opt.Expression)} ?? new object())",
                ZeroOrMore zom => GenerateZeroOrMore(zom),
                OneOrMore oom => GenerateOneOrMore(oom),
                PositiveLookahead pla => GenerateLookahead(pla, true),
                NegativeLookahead nla => GenerateLookahead(nla, false),
                Cut cut => GenerateCut(cut),
                Group group => GenerateGroup(group),
                _ => "null"
            };
        }

        private bool IsToken(string name)
        {
            return _tokens.Any(t => t.Name == name);
        }

        private string GenerateZeroOrMore(ZeroOrMore atom)
        {
            return $"ParseZeroOrMore(() => {GenerateAtomCode(atom.Expression)})";
        }

        private string GenerateOneOrMore(OneOrMore atom)
        {
            return $"ParseOneOrMore(() => {GenerateAtomCode(atom.Expression)})";
        }

        private string GenerateLookahead(PositiveLookahead atom, bool positive)
        {
            var op = positive ? "!=" : "==";
            return $"(Mark() is var pos && {GenerateAtomCode(atom.Expression)} {op} null ? (Reset(pos), new object()) : (Reset(pos), null))";
        }

        private string GenerateLookahead(NegativeLookahead atom, bool positive)
        {
            var op = positive ? "!=" : "==";
            return $"(Mark() is var pos && {GenerateAtomCode(atom.Expression)} {op} null ? (Reset(pos), new object()) : (Reset(pos), null))";
        }

        private string GenerateGroup(Group group)
        {
            // Generate inline group parsing to reduce method count
            if (group.Alternatives.Count == 0)
                return "null";

            if (group.Alternatives.Count == 1)
            {
                // Simple single alternative - generate inline
                var alt = group.Alternatives[0];
                if (alt.Items.Count == 1)
                {
                    return $"({GenerateAtomCode(alt.Items[0].Atom)})";
                }
            }

            // Complex group - still generate separate method but with better naming
            var groupId = _groupCounter++;
            return $"ParseGroup_{groupId}()";
        }

        private string ProcessAction(string action, Dictionary<string, string> variables)
        {
            // Simple variable substitution for now
            var result = action;
            foreach (var (name, varName) in variables)
            {
                result = result.Replace(name, varName);
            }
            return result;
        }

        private string ToCSharpMethodName(string grammarName)
        {
            // Convert grammar rule name to C# method name
            var parts = grammarName.Split('_');
            return string.Join("", parts.Select(p =>
                char.ToUpper(p[0]) + p.Substring(1).ToLower()));
        }

        private string TranslateCTypeToCS(string cType)
        {
            // Convert CPython C types to C# types
            return cType switch
            {
                "mod_ty" => "object?", // Python module type
                "asdl_stmt_seq*" => "List<object>?", // Statement sequence
                "asdl_expr_seq*" => "List<object>?", // Expression sequence
                "stmt_ty" => "object?", // Statement type
                "expr_ty" => "object?", // Expression type
                "asdl_seq*" => "List<object>?", // Generic sequence
                "string" => "string?",
                "int" => "int",
                "void" => "void",
                _ when cType.EndsWith("*") => "List<object>?", // Generic pointer types become lists
                _ when cType.Contains("_ty") => "object?", // AST node types become objects
                _ => cType // Keep as-is for standard types
            };
        }

        private string GenerateCut(Cut cut)
        {
            // In PEG, the cut operator (~) commits to the current choice and prevents backtracking
            // For simplicity, we'll generate the expression but add a comment about the cut semantics
            return $"({GenerateAtomCode(cut.Expression)} /* cut: no backtracking */)";
        }

        // Output helper methods
        private void WriteLine(string line = "")
        {
            if (!string.IsNullOrEmpty(line))
            {
                _output.Append(new string(' ', _indentLevel * 4));
                _output.AppendLine(line);
            }
            else
            {
                _output.AppendLine();
            }
        }

        private void Indent() => _indentLevel++;
        private void Dedent() => _indentLevel--;
    }
}