// Generated tokenizer from Grammar/Tokens
// DO NOT EDIT - This file is automatically generated
// CPython 3.12 compatible tokenizer - Complete standalone implementation

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace SharpPy.Generated
{
    /// <summary>
    /// CPython 3.12: Equivalent of C's void* - base class for all generated types
    /// This replaces object type usage to maintain type safety
    /// All AST nodes, tokens, and helper types inherit from this
    /// </summary>
    public abstract class GeneratedPtr
    {
        // Minimal base class - just provides type hierarchy
    }

    /// <summary>
    /// CPython 3.12: Base class for all ASDL sequence types
    /// Equivalent to C's asdl_seq* - generic sequence container
    /// Contains List<GeneratedPtr> for void* sequence handling
    /// </summary>
    public class GeneratedSeq : GeneratedPtr, System.Collections.Generic.IList<GeneratedPtr>
    {
        protected List<GeneratedPtr> _items = new();

        public GeneratedSeq() { }
        public GeneratedSeq(int capacity) { _items = new List<GeneratedPtr>(capacity); }
        public GeneratedSeq(List<GeneratedPtr> weak_ref) { this._items = weak_ref; }
        public GeneratedSeq(IEnumerable<GeneratedPtr> collection) { _items = new List<GeneratedPtr>(collection); }

        // IList<GeneratedPtr> implementation
        public GeneratedPtr this[int index] { get => _items[index]; set => _items[index] = value; }
        public int Count => _items.Count;
        public bool IsReadOnly => false;
        public void Add(GeneratedPtr item) => _items.Add(item);
        public void Clear() => _items.Clear();
        public bool Contains(GeneratedPtr item) => _items.Contains(item);
        public void CopyTo(GeneratedPtr[] array, int arrayIndex) => _items.CopyTo(array, arrayIndex);
        public System.Collections.Generic.IEnumerator<GeneratedPtr> GetEnumerator() => _items.GetEnumerator();
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => _items.GetEnumerator();
        public int IndexOf(GeneratedPtr item) => _items.IndexOf(item);
        public void Insert(int index, GeneratedPtr item) => _items.Insert(index, item);
        public bool Remove(GeneratedPtr item) => _items.Remove(item);
        public void RemoveAt(int index) => _items.RemoveAt(index);

        // Additional List<T> methods for compatibility
        public void AddRange(System.Collections.Generic.IEnumerable<GeneratedPtr> collection) => _items.AddRange(collection);

        // Conversion methods
        /// <summary>Returns raw List<GeneratedPtr></summary>
        public List<GeneratedPtr> ToRawList() => _items;
        public List<T> ToCastList<T>() where T : GeneratedPtr
        {
            var result = new List<T>(_items.Count);
            foreach (var item in _items) result.Add((T)item);
            return result;
        }

        /// <summary>Converts GeneratedSeq to typed Seq subclass (e.g., GeneratedExprSeq)</summary>
        public T Cast<T>() where T : GeneratedSeq, new()
        {
            var result = new T();
            result._initialize(this._items);
            return result;
        }

        static public GeneratedSeq FromList(List<GeneratedPtr> items)
        {
            return new GeneratedSeq(items);
        }

        private void _initialize(List<GeneratedPtr> items)
        {
            this._items = items;
        }

        /// <summary>Converts to typed IEnumerable<T> with casting - LINQ replacement</summary>
        public System.Collections.Generic.IEnumerable<T> ToEnumerable<T>() where T : GeneratedPtr
        {
            foreach (var item in _items) yield return (T)item;
        }

        /// <summary>Filters sequence by predicate - LINQ Where replacement</summary>
        public GeneratedSeq Where(System.Func<GeneratedPtr, bool> predicate)
        {
            var result = new GeneratedSeq();
            foreach (var item in _items)
            {
                if (predicate(item)) result.Add(item);
            }
            return result;
        }

        /// <summary>Maps sequence by selector - LINQ Select replacement</summary>
        public GeneratedSeq Select<T>(System.Func<GeneratedPtr, T> selector) where T : GeneratedPtr
        {
            var result = new GeneratedSeq(_items.Count);
            foreach (var item in _items) result.Add(selector(item));
            return result;
        }

        // Type checking methods
        /// <summary>
        /// Checks if sequence contains mixed types (different runtime types)
        /// Returns false if all items are the same type, true if mixed
        /// Empty or single-item sequences return false
        /// </summary>
        public bool IsMixed()
        {
            if (_items.Count <= 1) return false;
            var firstType = _items[0]?.GetType();
            for (int i = 1; i < _items.Count; i++)
            {
                if (_items[i]?.GetType() != firstType) return true;
            }
            return false;
        }
    }

    /// <summary>
    /// CPython 3.12: Memoization entry for PEG parser
    /// Equivalent to: typedef struct _memo { int type; void *node; int mark; struct _memo *next; } Memo;
    /// </summary>
    public class MemoEntry
    {
        /// <summary>Rule type name (CPython uses int type ID, we use string for clarity)</summary>
        public string RuleType { get; set; } = "";
        /// <summary>Parsed result node (can be null for failed parse)</summary>
        public GeneratedPtr? Node { get; set; }
        /// <summary>Parser mark (position) after parsing this rule</summary>
        public int Mark { get; set; }
        // Note: CPython uses linked list (next pointer), we use List<MemoEntry> in Token
    }

    /// <summary>
    /// Token information interface for PegInterpreter compatibility
    /// </summary>
    public interface ITokenInfo
    {
        PyToken.Type Type { get; }
        string Value { get; }
        int Line { get; }
        int Column { get; }
    }

    /// <summary>
    /// CPython 3.12 compatible token info
    /// Inherits GeneratedPtr for void* compatibility
    /// Equivalent to: typedef struct { int type; PyObject *bytes; int lineno, col_offset; ...; Memo *memo; } Token;
    /// </summary>
    public class GeneratedTokenInfo : GeneratedPtr, ITokenInfo
    {
        public PyToken.Type Type { get; set; }
        public string Value { get; set; } = "";

        /// <summary>
        /// CPython 3.12: Parenthesis nesting level (depth of nested parentheses/brackets/braces)
        /// Used to track context for error reporting and syntax validation
        /// Corresponds to Token.level in CPython's pegen.h
        /// </summary>
        public int Level { get; set; }

        public int Line { get; set; }
        public int Column { get; set; }
        public int EndLine { get; set; }
        public int EndColumn { get; set; }

        /// <summary>
        /// CPython 3.12: Memoization cache for this token
        /// Each token owns its memoization entries (like Token.memo linked list in C)
        /// </summary>
        public List<MemoEntry>? Memo { get; set; }

        public GeneratedTokenInfo(PyToken.Type type, string value, int line, int column, int endLine, int endColumn)
        {
            Type = type;
            Value = value;
            Level = 0; // Default level is 0 (not inside any parentheses)
            Line = line;
            Column = column;
            EndLine = endLine;
            EndColumn = endColumn;
        }
    }

    /// <summary>
    /// Parser context types for tracking parsing state - CPython 3.12 compatible
    /// </summary>
    public enum ContextType
    {
        Module,
        Function,
        Class,
        Loop,
        Async,
        Lambda,
        Comprehension
    }

    /// <summary>
    /// Parser context information for validation
    /// </summary>
    public class ParserContext
    {
        public ContextType Type { get; set; }
        public int NestingLevel { get; set; }
        public int StartPosition { get; set; }
        public string? Name { get; set; } // Function/class name for debugging

        public ParserContext(ContextType type, int nestingLevel = 0, int startPosition = 0, string? name = null)
        {
            Type = type;
            NestingLevel = nestingLevel;
            StartPosition = startPosition;
            Name = name;
        }

        public override string ToString()
        {
            var name = Name ?? "anonymous";
            return $"{Type}({name}) at level {NestingLevel}, pos {StartPosition}";
        }
    }

    /// <summary>
    /// Generated tokenizer for Python 3.12 grammar
    /// </summary>
    public class Tokenizer
    {
        private readonly string _source;
        private int _position;
        private int _line = 1;
        private int _column = 0; // CPython uses 0-based column indexing
        private readonly List<GeneratedTokenInfo> _tokens = new();

        // INDENT/DEDENT handling
        private readonly Stack<int> _indentStack = new();
        private bool _atLineStart = true;
        private readonly Queue<GeneratedTokenInfo> _pendingTokens = new();

        // Line state tracking for NL vs NEWLINE distinction
        private bool _currentLineHasRealTokens = false;

        // Parentheses context tracking for correct NL/NEWLINE classification
        private readonly Stack<char> _parenStack = new();
        private bool IsInsideParentheses => _parenStack.Count > 0;

        // CPython 3.12: Parenthesis nesting level tracking (tok->level in CPython)
        // Increments on '(', '[', '{' and decrements on ')', ']', '}'
        private int _level = 0;

        // CPython 3.12: Colon context tracking for compound statement NEWLINE tokens
        // Rule: colon-followed-by-newline always generates NEWLINE token (not NL)
        private bool _lastTokenWasColon = false;

        // F-string state tracking for PEP 701 (Python 3.12)
        private bool _insideFString = false;
        private int _fstringBraceDepth = 0;
        private char _fstringQuoteChar = '\0';
        private int _fstringQuoteSize = 0;

        // NEWLINE position tracking for \r\n sequences
        // When we encounter \r followed by \n, we save the column before Advance() processes \r
        private int _savedNewlineColumn = -1;

        public Tokenizer(string source)
        {
            _source = source ?? throw new ArgumentNullException(nameof(source));
            _position = 0;
            _indentStack.Push(0); // Initialize with base indentation level
        }

        /// <summary>
        /// Tokenize the source code
        /// </summary>
        public List<GeneratedTokenInfo> Tokenize()
        {
            #if DEBUG_TOKEN_LOG
            Console.WriteLine("[DEBUG] Tokenize() method started");
            #endif
            _tokens.Clear();
            _position = 0;
            _line = 1;
            _column = 0; // CPython uses 0-based column indexing
            _currentLineHasRealTokens = false; // Reset line state tracking
            #if DEBUG_TOKEN_LOG
            Console.WriteLine($"[DEBUG] Source length: {_source.Length}, Source: '{_source}'");
            #endif

            // TODO: ENCODING token is commented out for .NET Core compatibility
            // CPython always emits ENCODING as first token (0,0-0,0: ENCODING 'utf-8')
            // .NET Core handles encoding differently, so this is not critical
            // Skip ENCODING token for compatibility with CPython generate_tokens()
            // AddToken(PyToken.Type.ENCODING, "utf-8", 0, 0);

            #if DEBUG_TOKEN_LOG
            Console.WriteLine("[DEBUG] Starting main tokenization loop");
            #endif
            while (_position < _source.Length)
            {
                var startPosition = _position; // Track position for infinite loop detection
                #if DEBUG_TOKEN_LOG
                Console.WriteLine($"[DEBUG] Loop iteration: position={_position}, char='{CurrentChar}', ASCII={(int)CurrentChar}");
                #endif

                // Process indentation at start of line before any other tokens
                if (_atLineStart)
                {
                    #if DEBUG_TOKEN_LOG
                    Console.WriteLine("[DEBUG] Calling HandleIndentation");
                    #endif
                    HandleIndentation();
                    #if DEBUG_TOKEN_LOG
                    Console.WriteLine("[DEBUG] HandleIndentation completed");
                    #endif
                    ProcessPendingTokens();
                }

                // CPython 3.12: Physical line continuation (backslash + newline)
                // Outside strings: x = 1 + \<newline>    2  →  x = 1 + 2
                // This is different from escape sequences inside strings
                if (CurrentChar == '\\' && !_insideFString)
                {
                    // Check if next character is newline (line continuation)
                    if (_position + 1 < _source.Length && (_source[_position + 1] == '\n' || _source[_position + 1] == '\r'))
                    {
                        #if DEBUG_TOKEN_LOG
                        Console.WriteLine($"[DEBUG] Line continuation detected at position {_position}");
                        #endif
                        // Skip backslash
                        _position++;
                        _column++;

                        // Skip newline characters WITHOUT setting _atLineStart (this is line joining)
                        if (CurrentChar == '\r' && _position + 1 < _source.Length && _source[_position + 1] == '\n')
                        {
                            // \r\n sequence
                            _position++; // Skip \r
                            _line++;
                            _column = 0;
                            _position++; // Skip \n
                        }
                        else if (CurrentChar == '\r')
                        {
                            // Standalone \r
                            _position++;
                            _line++;
                            _column = 0;
                        }
                        else if (CurrentChar == '\n')
                        {
                            // \n
                            _position++;
                            _line++;
                            _column = 0;
                        }

                        // CRITICAL: Do NOT set _atLineStart - this is a continuation, not a new logical line
                        // Continue to next iteration - the physical line is joined
                        continue;
                    }
                    // If backslash is not followed by newline, fall through to error handling
                }

                if (char.IsWhiteSpace(CurrentChar) || CurrentChar == '\r')
                {
                    #if DEBUG_TOKEN_LOG
                    Console.WriteLine($"[DEBUG] Calling HandleWhitespace at position {_position}, char='{CurrentChar}', ASCII={(int)CurrentChar}");
                    #endif
                    HandleWhitespace();
                }
                else if (CurrentChar == '#')
                {
                    HandleComment();
                }
                else if (char.IsLetter(CurrentChar) || CurrentChar == '_')
                {
                    HandleName();
                }
                else if (char.IsDigit(CurrentChar))
                {
                    HandleNumber();
                }
                else if (CurrentChar == '\"' || CurrentChar == '\'')
                {
                    HandleString();
                }
                else if(HandleLiteral()){}
                else
                {
                    AddToken(PyToken.Type.ERRORTOKEN, CurrentChar.ToString(), _line, _column);
                    _currentLineHasRealTokens = true; // Mark line as having real tokens
                    Advance();
                }

                // CRITICAL: Infinite loop protection
                if (_position == startPosition)
                {
                    // Console.WriteLine($"[ERROR] Tokenizer infinite loop detected at position {_position}, char: '{CurrentChar}'. Forcing advance.");
                    // Advance(); // Force advance to prevent infinite loop
                    throw new InvalidOperationException($"Tokenizer infinite loop detected at position {_position}, char: '{CurrentChar}'");
                }
            }

            // Add final NEWLINE if file doesn't end with newline (BEFORE DEDENT for CPython compatibility)
            if (_position > 0 && _source[_position - 1] != '\n' && _source[_position - 1] != '\r')
            {
                AddToken(PyToken.Type.NEWLINE, "\n", _line, _column);
            }

            // Generate remaining DEDENT tokens at EOF
            while (_indentStack.Count > 1)
            {
                _indentStack.Pop();
                _pendingTokens.Enqueue(new GeneratedTokenInfo(PyToken.Type.DEDENT, "", _line + 1, 0, _line + 1, 1));
            }

            // Process any pending tokens at EOF
            ProcessPendingTokens();

            // Add ENDMARKER for compatibility with CPython generate_tokens()
            AddToken(PyToken.Type.ENDMARKER, "", _line, _column);
            return _tokens;
        }

        private char CurrentChar => _position < _source.Length ? _source[_position] : '\0';

        private void Advance()
        {
            if (_position < _source.Length)
            {
                if (_source[_position] == '\n')
                {
                    _line++;
                    _column = 0; // CPython uses 0-based column indexing
                    _atLineStart = true; // Next position will be start of new line
                    // NOTE: Do not reset _currentLineHasRealTokens here - it should be reset AFTER we decide NL vs NEWLINE
                }
                else if (_source[_position] == '\r')
                {
                    // Handle \r character for line tracking
                    _line++;
                    _column = 0; // CPython uses 0-based column indexing
                    _atLineStart = true; // Next position will be start of new line
                    // Check if this is followed by \n (Windows CRLF)
                    if (_position + 1 < _source.Length && _source[_position + 1] == '\n')
                    {
                        // This is \r\n, advance past \r but don't double-increment line
                        _position++;
                        // The \n will be processed next and should not increment line again
                        // So we temporarily reset line tracking for the \n
                        _line--; // Compensate because \n handler will increment again
                        _atLineStart = false; // Let \n handler set this
                    }
                    else
                    {
                        // Standalone \r - advance normally
                        _position++;
                    }
                    return; // Early return to avoid double increment
                }
                else
                {
                    _column++;
                }
                _position++;
            }
        }

        private void AddToken(PyToken.Type type, string value, int startLine, int startColumn)
        {
            var token = new GeneratedTokenInfo(type, value, startLine, startColumn, startLine, startColumn + value.Length);
            token.Level = _level; // CPython 3.12: Assign current parenthesis nesting level
            _tokens.Add(token);
        }

        private void HandleWhitespace()
        {
            while (_position < _source.Length && char.IsWhiteSpace(CurrentChar))
            {
                #if DEBUG_TOKEN_LOG
                Console.WriteLine($"[DEBUG] HandleWhitespace loop: position={_position}, char='{CurrentChar}', ASCII={(int)CurrentChar}");
                #endif
                if (CurrentChar == '\r')
                {
                    // Handle \r character - could be part of \r\n sequence
                    #if DEBUG_TOKEN_LOG
                    Console.WriteLine($"[DEBUG] Found \r at position {_position}, checking next char...");
                    #endif
                    // FIXED: Save column BEFORE Advance() for \r\n NEWLINE token position
                    var savedColumnBeforeAdvance = _column;

                    // Check if next character is \n for Windows line ending
                    if (_position + 1 < _source.Length && _source[_position + 1] == '\n')
                    {
                        #if DEBUG_TOKEN_LOG
                        Console.WriteLine($"[DEBUG] Found \r\n sequence: skipping \r, will process \n next");
                        #endif
                        // This is a \r\n sequence, advance past \r and let \n handler process it
                        Advance(); // Skip \r, \n will be processed in next iteration
                        // Store the saved column for later use in \n handler via a class field
                        _savedNewlineColumn = savedColumnBeforeAdvance;
                        continue; // Continue loop to process \n character
                    }
                    else
                    {
                        // Standalone \r (Mac-style line ending) - treat as newline
                        var newlineColumn = _column;
                        var newlineValue = "\r";

                        // CPython 3.12: Inside parentheses always NL, even after colon
                        if (IsInsideParentheses)
                        {
                            AddToken(PyToken.Type.NL, newlineValue, _line, newlineColumn);
                            // Process pending DEDENT tokens after NL
                            ProcessPendingTokens();
                            _lastTokenWasColon = false; // Reset after processing
                        }
                        // CPython 3.12: Colon-followed-by-newline generates NEWLINE token (only outside parentheses)
                        else if (_lastTokenWasColon)
                        {
                            #if DEBUG_TOKEN_LOG
                            Console.WriteLine($"[DEBUG] Generating NEWLINE token after colon (standalone \r): value='{newlineValue}', line={_line}, col={newlineColumn}");
                            #endif
                            AddToken(PyToken.Type.NEWLINE, newlineValue, _line, newlineColumn);
                            _lastTokenWasColon = false; // Reset after processing
                        }
                        // Outside parentheses: check if blank line
                        else
                        {
                            bool isBlankLine = IsBlankLine();
                            if (isBlankLine)
                            {
                                AddToken(PyToken.Type.NL, newlineValue, _line, newlineColumn);
                                // Process pending DEDENT tokens after NL
                                ProcessPendingTokens();
                            }
                            else
                            {
                                AddToken(PyToken.Type.NEWLINE, newlineValue, _line, newlineColumn);
                            }
                        }
                        _atLineStart = true;
                        // Process pending DEDENT tokens after NEWLINE
                        ProcessPendingTokens();
                        _currentLineHasRealTokens = false; // Reset for new line
                        Advance();
                        // Indentation will be handled at the start of the main loop
                        break; // Stop processing whitespace after handling newline
                    }
                }
                else if (CurrentChar == '\n')
                {
                    #if DEBUG_TOKEN_LOG
                    Console.WriteLine($"[DEBUG] Found \n at position {_position}, processing newline...");
                    #endif
                    // Store newline position before advancing - CPython uses start position
                    var newlineColumn = _column;
                    // Check for \r\n sequence (Windows line ending)
                    var newlineValue = "\n";
                    if (_position > 0 && _source[_position - 1] == '\r')
                    {
                        // FIXED: For \r\n sequences, use the saved column from before \r Advance()
                        // This gives us the correct position where \r\n started
                        newlineValue = "\r\n";
                        newlineColumn = _savedNewlineColumn >= 0 ? _savedNewlineColumn : newlineColumn;
                        _savedNewlineColumn = -1; // Reset after use
                    }

                    // CPython 3.12: Inside parentheses always NL, even after colon
                    if (IsInsideParentheses)
                    {
                        AddToken(PyToken.Type.NL, newlineValue, _line, newlineColumn);
                        // Process pending DEDENT tokens after NL
                        ProcessPendingTokens();
                        _lastTokenWasColon = false; // Reset after processing
                    }
                    // CPython 3.12: Colon-followed-by-newline generates NEWLINE token (only outside parentheses)
                    else if (_lastTokenWasColon)
                    {
                        #if DEBUG_TOKEN_LOG
                        Console.WriteLine($"[DEBUG] Generating NEWLINE token after colon (\n processing): value='{newlineValue}', line={_line}, col={newlineColumn}");
                        #endif
                        AddToken(PyToken.Type.NEWLINE, newlineValue, _line, newlineColumn);
                        _lastTokenWasColon = false; // Reset after processing
                    }
                    // Outside parentheses: check if blank line
                    else
                    {
                        bool isBlankLine = IsBlankLine();
                        if (isBlankLine)
                        {
                            AddToken(PyToken.Type.NL, newlineValue, _line, newlineColumn);
                            // Process pending DEDENT tokens after NL
                            ProcessPendingTokens();
                        }
                        else
                        {
                            AddToken(PyToken.Type.NEWLINE, newlineValue, _line, newlineColumn);
                        }
                    }
                    _atLineStart = true;
                    // Process pending DEDENT tokens after NEWLINE
                    ProcessPendingTokens();
                    _currentLineHasRealTokens = false; // Reset for new line
                    Advance();
                    // Indentation will be handled at the start of the main loop
                    break; // Stop processing whitespace after handling newline
                }
                Advance();
            }
            #if DEBUG_TOKEN_LOG
            Console.WriteLine($"[DEBUG] HandleWhitespace method ended: position={_position}, char='{CurrentChar}', ASCII={(int)CurrentChar}");
            #endif
        }

        private bool IsBlankLine()
        {
            // A blank line is one that contains only comments and/or whitespace
            // CPython rule: if no real tokens on current line, it's blank
            return !_currentLineHasRealTokens;
        }

        private void ProcessPendingTokens()
        {
            while (_pendingTokens.Count > 0)
            {
                var pending = _pendingTokens.Dequeue();
                _tokens.Add(pending);
            }
        }

        private void HandleComment()
        {
            var start = _position;
            var startLine = _line;
            var startColumn = _column;
            while (_position < _source.Length && CurrentChar != '\n')
            {
                Advance();
            }
            var comment = _source.Substring(start, _position - start);
            AddToken(PyToken.Type.COMMENT, comment, startLine, startColumn);
        }

        private void HandleName()
        {
            var start = _position;
            var startLine = _line;
            var startColumn = _column;

            // Check for string prefixes first (r, b, rb, br, f, fr, rf)
            // Also check for numeric string prefixes that might be confused
            if (IsStringPrefix())
            {
                HandleString();
                return;
            }

            while (_position < _source.Length && (char.IsLetterOrDigit(CurrentChar) || CurrentChar == '_'))
            {
                Advance();
            }
            var name = _source.Substring(start, _position - start);

            PyToken.Type tokenType = PyToken.Type.NAME;
            AddToken(tokenType, name, startLine, startColumn);
            _currentLineHasRealTokens = true; // Mark line as having real tokens
        }

        private void HandleNumber()
        {
            var start = _position;
            var startLine = _line;
            var startColumn = _column;

            // Check for special prefixes: 0x, 0X, 0o, 0O, 0b, 0B
            if (CurrentChar == '0' && _position + 1 < _source.Length)
            {
                char nextChar = char.ToLower(_source[_position + 1]);
                if (nextChar == 'x')
                {
                    // Hexadecimal number
                    Advance(); // Skip '0'
                    Advance(); // Skip 'x' or 'X'
                    while (_position < _source.Length && (char.IsDigit(CurrentChar) || (char.ToLower(CurrentChar) >= 'a' && char.ToLower(CurrentChar) <= 'f') || CurrentChar == '_'))
                    {
                        Advance();
                    }
                }
                else if (nextChar == 'o')
                {
                    // Octal number
                    Advance(); // Skip '0'
                    Advance(); // Skip 'o' or 'O'
                    while (_position < _source.Length && (CurrentChar >= '0' && CurrentChar <= '7' || CurrentChar == '_'))
                    {
                        Advance();
                    }
                }
                else if (nextChar == 'b')
                {
                    // Binary number
                    Advance(); // Skip '0'
                    Advance(); // Skip 'b' or 'B'
                    while (_position < _source.Length && (CurrentChar == '0' || CurrentChar == '1' || CurrentChar == '_'))
                    {
                        Advance();
                    }
                }
                else
                {
                    // Regular number starting with 0
                    ParseDecimalNumber();
                }
            }
            else
            {
                // Regular decimal number
                ParseDecimalNumber();
            }

            // Check for complex number suffix (j/J)
            if (_position < _source.Length && char.ToLower(CurrentChar) == 'j')
            {
                Advance();
            }

            var number = _source.Substring(start, _position - start);
            AddToken(PyToken.Type.NUMBER, number, startLine, startColumn);
            _currentLineHasRealTokens = true; // Mark line as having real tokens
        }

        private void ParseDecimalNumber()
        {
            // Parse integer part
            while (_position < _source.Length && (char.IsDigit(CurrentChar) || CurrentChar == '_'))
            {
                Advance();
            }

            // Check for decimal point
            if (_position < _source.Length && CurrentChar == '.')
            {
                Advance(); // Skip '.'
                // Parse fractional part
                while (_position < _source.Length && (char.IsDigit(CurrentChar) || CurrentChar == '_'))
                {
                    Advance();
                }
            }

            // Check for scientific notation (e/E)
            if (_position < _source.Length && char.ToLower(CurrentChar) == 'e')
            {
                Advance(); // Skip 'e' or 'E'
                // Check for optional sign
                if (_position < _source.Length && (CurrentChar == '+' || CurrentChar == '-'))
                {
                    Advance();
                }
                // Parse exponent
                while (_position < _source.Length && (char.IsDigit(CurrentChar) || CurrentChar == '_'))
                {
                    Advance();
                }
            }
        }

        private void HandleString()
        {
            var start = _position;
            var startLine = _line;
            var startColumn = _column;

            // Check for f-string prefix (f, F, rf, fr, RF, FR)
            bool isFString = false;
            int prefixEnd = _position;
            while (prefixEnd < _source.Length && char.IsLetter(_source[prefixEnd]))
            {
                char c = char.ToLower(_source[prefixEnd]);
                if (c == 'f')
                {
                    isFString = true;
                }
                prefixEnd++;
            }

            // If this is an f-string, delegate to HandleFString
            if (isFString && prefixEnd < _source.Length && (_source[prefixEnd] == '\"' || _source[prefixEnd] == '\''))
            {
                HandleFString();
                return;
            }

            // Skip any string prefix (r, b, rb, br)
            while (_position < _source.Length && char.IsLetter(CurrentChar))
            {
                Advance();
            }

            // Now we should be at the quote
            if (_position >= _source.Length || (CurrentChar != '\"' && CurrentChar != '\''))
            {
                // Not a valid string, treat as regular name
                _position = start; // Reset position
                while (_position < _source.Length && (char.IsLetterOrDigit(CurrentChar) || CurrentChar == '_'))
                {
                    Advance();
                }
                var name = _source.Substring(start, _position - start);
                AddToken(PyToken.Type.NAME, name, startLine, startColumn);
                _currentLineHasRealTokens = true; // Mark line as having real tokens
                return;
            }

            var quote = CurrentChar;

            // Check for triple-quoted strings
            if (_position + 2 < _source.Length && _source[_position + 1] == quote && _source[_position + 2] == quote)
            {
                HandleTripleQuotedString(quote, start, startLine, startColumn);
            }
            else
            {
                HandleRegularString(quote, start, startLine, startColumn);
            }
        }

        private void HandleTripleQuotedString(char quote, int start, int startLine, int startColumn)
        {
            _position += 3; // Skip opening triple quotes

            // Read until closing triple quotes
            while (_position + 2 < _source.Length)
            {
                if (_source[_position] == quote && _source[_position + 1] == quote && _source[_position + 2] == quote)
                {
                    _position += 3; // Skip closing triple quotes
                    break;
                }
                Advance(); // This handles line counting for multiline strings
            }

            var str = _source.Substring(start, _position - start);
            AddToken(PyToken.Type.STRING, str, startLine, startColumn);
            _currentLineHasRealTokens = true; // Mark line as having real tokens
        }

        private void HandleRegularString(char quote, int start, int startLine, int startColumn)
        {
            Advance(); // Skip opening quote

            while (_position < _source.Length && CurrentChar != quote)
            {
                if (CurrentChar == '\\' && _position + 1 < _source.Length)
                {
                    Advance(); // Skip escape character
                }
                Advance();
            }

            if (_position < _source.Length)
            {
                Advance(); // Skip closing quote
            }

            var str = _source.Substring(start, _position - start);
            AddToken(PyToken.Type.STRING, str, startLine, startColumn);
            _currentLineHasRealTokens = true; // Mark line as having real tokens
        }

        private bool HandleLiteral()
        {
            var index = PyToken.GetLiteralIndex(_source, _position);
            if (index == -1)
                return false;

            var lit = PyToken.Literals[index];

            // CPython 3.12: Track parenthesis nesting level (tok->level in tokenizer.c lines 2560-2576)
            // Pattern: Token gets CURRENT level, THEN level changes
            // Before '(': level=0 → token.level=0 → increment to level=1
            // Before ')': level=1 → decrement to level=0 → token.level=0

            // Decrement BEFORE creating token for closing parens
            if (lit.type == PyToken.Type.RPAR || lit.type == PyToken.Type.RSQB || lit.type == PyToken.Type.RBRACE)
            {
                if (_level > 0)
                    _level--;
            }

            AddToken(lit.type, lit.name, _line, _column);

            // Increment AFTER creating token for opening parens
            if (lit.type == PyToken.Type.LPAR || lit.type == PyToken.Type.LSQB || lit.type == PyToken.Type.LBRACE)
            {
                _level++;
            }

            _position += lit.name.Length;
            _column += lit.name.Length;

            return true;
        }

        // 일단 f-string 은 무시
        private void HandleIndentation()
        {
            #if DEBUG_TOKEN_LOG
            Console.WriteLine($"[DEBUG] HandleIndentation: _atLineStart={_atLineStart}, position={_position}");
            #endif
            if (!_atLineStart) return;
            // Skip indentation processing inside parentheses
            if (IsInsideParentheses)
            {
                #if DEBUG_TOKEN_LOG
                Console.WriteLine("[DEBUG] Inside parentheses, setting _atLineStart=false");
                #endif
                _atLineStart = false; // CRITICAL: Must set this to avoid infinite loop
                return;
            }

            // Calculate current line indentation
            int indent = 0;
            int indentStartColumn = _column; // Save start position for INDENT token
            while (_position < _source.Length && (CurrentChar == ' ' || CurrentChar == '\t'))
            {
                indent += (CurrentChar == '\t' ? 8 : 1);
                Advance();
            }

            // CPython 3.12: Handle empty lines and comments for indentation
            #if DEBUG_TOKEN_LOG
            Console.WriteLine($"[DEBUG] Checking empty line: position={_position}, length={_source.Length}, char='{CurrentChar}'");
            #endif
            if (_position >= _source.Length || CurrentChar == '\n' || CurrentChar == '\r' || CurrentChar == '#')
            {
                #if DEBUG_TOKEN_LOG
                Console.WriteLine("[DEBUG] Empty line detected, setting _atLineStart=false");
                #endif
                _atLineStart = false; // CRITICAL: Must set this to avoid infinite loop
                // CPython 3.12: Don't process indentation for empty/comment lines
                // DEDENT tokens will be generated when we encounter the next non-empty line
                return;
            }

            // Handle indentation changes
            int currentLevel = _indentStack.Peek();
            if (indent > currentLevel)
            {
                // Increased indentation - INDENT
                // CPython 3.12: Only generate INDENT if we're actually increasing indentation
                _indentStack.Push(indent);
                var indentText = new string(' ', indent);
                AddToken(PyToken.Type.INDENT, indentText, _line, indentStartColumn);
                #if DEBUG_TOKEN_LOG
                Console.WriteLine($"[DEBUG] Generated INDENT token: level {currentLevel} -> {indent}");
                #endif
            }
            else if (indent < currentLevel)
            {
                // Decreased indentation - DEDENT(s)
                while (_indentStack.Count > 1 && _indentStack.Peek() > indent)
                {
                    _indentStack.Pop();
                    // CPython 3.12: DEDENT position should point to current indentation level
                    // Use current position (start of current token) not previous position
                    _pendingTokens.Enqueue(new GeneratedTokenInfo(PyToken.Type.DEDENT, "", _line, indent, _line, indent + 1));
                }

                // Check for indentation error
                if (_indentStack.Count > 0 && _indentStack.Peek() != indent)
                {
                    throw new InvalidOperationException($"IndentationError: unindent does not match any outer indentation level at line {_line}");
                }
            }

            #if DEBUG_TOKEN_LOG
            Console.WriteLine("[DEBUG] Setting _atLineStart=false at end of HandleIndentation");
            #endif
            _atLineStart = false;
            // Now that we're starting to process this line, reset the line state for real token tracking
            _currentLineHasRealTokens = false;
            #if DEBUG_TOKEN_LOG
            Console.WriteLine("[DEBUG] HandleIndentation method ending normally");
            #endif
        }

        private bool IsStringPrefix()
        {
            // Check for string prefixes: r, b, rb, br, f, fr, rf
            if (_position < _source.Length)
            {
                char c = char.ToLower(CurrentChar);
                if (c == 'r' || c == 'b' || c == 'f')
                {
                    // Check if followed by quote or another prefix
                    if (_position + 1 < _source.Length)
                    {
                        char next = _source[_position + 1];
                        if (next == '\"' || next == '\'')
                        {
                            return true; // Single prefix like r", b", f"
                        }
                        else if (_position + 2 < _source.Length)
                        {
                            char next2 = char.ToLower(_source[_position + 1]);
                            char next3 = _source[_position + 2];
                            if ((c == 'r' && next2 == 'b') || (c == 'b' && next2 == 'r') || (c == 'f' && next2 == 'r') || (c == 'r' && next2 == 'f'))
                            {
                                if (next3 == '\"' || next3 == '\'')
                                {
                                    return true; // Double prefix like rb", br", fr", rf"
                                }
                            }
                        }
                    }
                }
            }
            return false;
        }

        /// <summary>
        /// CPython 3.12 PEP 701: F-string tokenization
        /// F-strings are tokenized into: FSTRING_START, expression tokens, FSTRING_MIDDLE, FSTRING_END
        /// </summary>
        private void HandleFString()
        {
            var start = _position;
            var startLine = _line;
            var startColumn = _column;

            // Skip prefix (f, F, rf, fr, RF, FR)
            bool isRawFString = false;
            while (_position < _source.Length && char.IsLetter(CurrentChar))
            {
                char c = char.ToLower(CurrentChar);
                if (c == 'r') isRawFString = true;
                Advance();
            }

            // Now we should be at the quote
            if (_position >= _source.Length || (CurrentChar != '\"' && CurrentChar != '\''))
            {
                throw new InvalidOperationException($"F-string format error at line {_line}, column {_column}");
            }

            _fstringQuoteChar = CurrentChar;
            Advance(); // Skip opening quote

            // Check for triple-quoted f-string
            _fstringQuoteSize = 1;
            if (_position + 1 < _source.Length && _source[_position] == _fstringQuoteChar && _source[_position + 1] == _fstringQuoteChar)
            {
                _fstringQuoteSize = 3;
                Advance(); // Skip second quote
                Advance(); // Skip third quote
            }

            // Emit FSTRING_START token
            var fstringStart = _source.Substring(start, _position - start);
            AddToken(PyToken.Type.FSTRING_START, fstringStart, startLine, startColumn);
            _currentLineHasRealTokens = true;

            // Enter f-string mode
            _insideFString = true;
            _fstringBraceDepth = 0;

            // Process f-string content
            HandleFStringContent(isRawFString);

            // Reset _atLineStart flag that might have been set during f-string processing
            _atLineStart = false;
        }

        /// <summary>
        /// Process f-string content: literals and expressions
        /// </summary>
        private void HandleFStringContent(bool isRawFString)
        {
            var literalStart = _position;
            var literalStartLine = _line;
            var literalStartColumn = _column;

            while (_position < _source.Length)
            {
                // Check for closing quotes
                if (IsAtFStringEnd())
                {
                    // Emit any pending FSTRING_MIDDLE before ending
                    if (_position > literalStart)
                    {
                        var middleContent = _source.Substring(literalStart, _position - literalStart);
                        AddToken(PyToken.Type.FSTRING_MIDDLE, middleContent, literalStartLine, literalStartColumn);
                        _currentLineHasRealTokens = true;
                    }

                    // Emit FSTRING_END token
                    var endStart = _position;
                    var endLine = _line;
                    var endColumn = _column;
                    for (int i = 0; i < _fstringQuoteSize; i++)
                    {
                        Advance();
                    }
                    var fstringEnd = _source.Substring(endStart, _position - endStart);
                    AddToken(PyToken.Type.FSTRING_END, fstringEnd, endLine, endColumn);
                    _currentLineHasRealTokens = true;

                    // Exit f-string mode
                    _insideFString = false;
                    return;
                }

                char c = CurrentChar;

                // Handle opening brace (expression start)
                if (c == '{')
                {
                    var braceColumn = _column;
                    Advance();

                    // Check for escaped brace {{
                    if (_position < _source.Length && CurrentChar == '{')
                    {
                        // This is an escaped {{, include in FSTRING_MIDDLE
                        Advance();
                        continue;
                    }
                    else
                    {
                        // Emit FSTRING_MIDDLE for content before expression
                        if (_position - 1 > literalStart)
                        {
                            var middleContent = _source.Substring(literalStart, _position - 1 - literalStart);
                            AddToken(PyToken.Type.FSTRING_MIDDLE, middleContent, literalStartLine, literalStartColumn);
                            _currentLineHasRealTokens = true;
                        }

                        // Emit { as OP token (track level for CPython 3.12 compatibility)
                        AddToken(PyToken.Type.LBRACE, "{", _line, braceColumn);
                        _currentLineHasRealTokens = true;
                        _level++; // Increment level after creating LBRACE token
                        _fstringBraceDepth++;

                        // Tokenize expression content until matching }
                        HandleFStringExpression();

                        // After expression, reset literal start
                        literalStart = _position;
                        literalStartLine = _line;
                        literalStartColumn = _column;
                        continue;
                    }
                }

                // Handle closing brace (expression end)
                if (c == '}')
                {
                    Advance();

                    // Check for escaped brace }}
                    if (_position < _source.Length && CurrentChar == '}')
                    {
                        // This is an escaped }}, include in FSTRING_MIDDLE
                        Advance();
                        continue;
                    }
                    else
                    {
                        // Unmatched closing brace outside expression
                        throw new InvalidOperationException($"F-string: single '}}' is not allowed at line {_line}, column {_column}");
                    }
                }

                // Regular character, continue accumulating
                Advance();
            }

            // Unterminated f-string
            throw new InvalidOperationException($"Unterminated f-string literal at line {_line}, column {_column}");
        }

        /// <summary>
        /// Emit FSTRING_MIDDLE token for literal content between expressions
        /// </summary>
        private void EmitFStringMiddle(int start, int startLine, int startColumn)
        {
            if (_position > start)
            {
                var middleContent = _source.Substring(start, _position - start);
                AddToken(PyToken.Type.FSTRING_MIDDLE, middleContent, startLine, startColumn);
                _currentLineHasRealTokens = true;
            }
        }

        /// <summary>
        /// Check if we're at the end of the f-string
        /// </summary>
        private bool IsAtFStringEnd()
        {
            if (_position + _fstringQuoteSize > _source.Length)
                return false;

            for (int i = 0; i < _fstringQuoteSize; i++)
            {
                if (_source[_position + i] != _fstringQuoteChar)
                    return false;
            }

            return true;
        }

        /// <summary>
        /// Tokenize expression inside f-string braces
        /// </summary>
        private void HandleFStringExpression()
        {
            while (_position < _source.Length)
            {
                char c = CurrentChar;

                // Check for closing brace
                if (c == '}' && _fstringBraceDepth > 0)
                {
                    // Decrement level BEFORE creating RBRACE token (CPython 3.12 compatibility)
                    if (_level > 0)
                        _level--;
                    // Emit } as OP token
                    AddToken(PyToken.Type.RBRACE, "}", _line, _column);
                    _currentLineHasRealTokens = true;
                    _fstringBraceDepth--;
                    Advance();
                    return;
                }

                // Handle nested braces (like in dict literals inside f-string)
                if (c == '{')
                {
                    AddToken(PyToken.Type.LBRACE, "{", _line, _column);
                    _currentLineHasRealTokens = true;
                    _level++; // Increment level AFTER creating LBRACE token (CPython 3.12 compatibility)
                    _fstringBraceDepth++;
                    Advance();
                    continue;
                }

                // Tokenize expression content normally
                if (char.IsWhiteSpace(c) && c != '\n' && c != '\r')
                {
                    Advance();
                }
                else if (c == '\n' || c == '\r')
                {
                    // Newlines inside f-string expressions are not allowed (for single-quoted f-strings)
                    if (_fstringQuoteSize == 1)
                    {
                        throw new InvalidOperationException($"F-string expression: unterminated string at line {_line}, column {_column}");
                    }
                    Advance();
                }
                else if (c == '#')
                {
                    HandleComment();
                }
                else if (char.IsLetter(c) || c == '_')
                {
                    HandleName();
                }
                else if (char.IsDigit(c))
                {
                    HandleNumber();
                }
                else if (c == '\"' || c == '\'')
                {
                    // Check if this quote is the f-string closing quote
                    // If so, it's a syntax error (expression not closed)
                    if (c == _fstringQuoteChar && IsAtFStringEnd())
                    {
                        throw new InvalidOperationException($"F-string expression: unterminated expression at line {_line}, column {_column}");
                    }
                    HandleString();
                }
                else if (HandleLiteral())
                {
                    // Literal handled
                }
                else
                {
                    AddToken(PyToken.Type.ERRORTOKEN, c.ToString(), _line, _column);
                    _currentLineHasRealTokens = true;
                    Advance();
                }
            }

            throw new InvalidOperationException($"Unterminated f-string expression at line {_line}, column {_column}");
        }
    }
}
