
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SharpPy.Tokenizer
{
    /// <summary>
    /// Generates C# tokenizer code from PEG grammar tokens
    /// CPython 3.12 compatible tokenizer generation
    /// </summary>
    public class CSharpTokenizerGenerator
    {
        private readonly List<TokenDefinition> _tokens;
        private readonly StringBuilder _output;
        private int _indentLevel;

        public CSharpTokenizerGenerator(List<TokenDefinition> tokens)
        {
            _tokens = tokens;
            _output = new StringBuilder();
            _indentLevel = 0;
        }

        /// <summary>
        /// Generate the complete C# tokenizer class
        /// </summary>
        public string GenerateTokenizer()
        {
            GenerateHeader();
            GenerateTokenizerClass();
            return _output.ToString();
        }

        private void GenerateHeader()
        {
            WriteLine("// Generated tokenizer from Grammar/Tokens");
            WriteLine("// DO NOT EDIT - This file is automatically generated");
            WriteLine("// CPython 3.12 compatible tokenizer - Complete standalone implementation");
            WriteLine();
            WriteLine("using System;");
            WriteLine("using System.Collections.Generic;");
            WriteLine("using System.Linq;");
            WriteLine("using System.Text;");
            WriteLine("using System.Text.RegularExpressions;");
            WriteLine();
        }

        private void GenerateTokenizerClass()
        {
            WriteLine("namespace SharpPy.Generated");
            WriteLine("{");
            Indent();

            // GeneratedPtr is now defined in GeneratedAstTypes.cs
            GenerateTokenTypeEnum(); // Generate enum from Grammar/Tokens
            GenerateTokenInfoClass();
            GenerateGeneratedTokenizerClass();

            Dedent();
            WriteLine("}"); // Close namespace
        }

        private void GenerateTokenTypeEnum()
        {
            WriteLine("/// <summary>");
            WriteLine("/// CPython 3.12 compatible token types");
            WriteLine("/// </summary>");
            WriteLine("public enum GeneratedTokenType");
            WriteLine("{");
            Indent();

            foreach (var token in _tokens)
            {
                WriteLine($"{token.Name},");
            }

            Dedent();
            WriteLine("}");
            WriteLine();
        }

        private void GenerateTokenInfoClass()
        {
            // Generate ITokenInfo interface first (for PegInterpreter compatibility)
            WriteLine("/// <summary>");
            WriteLine("/// Token information interface for PegInterpreter compatibility");
            WriteLine("/// </summary>");
            WriteLine("public interface ITokenInfo");
            WriteLine("{");
            Indent();
            WriteLine("GeneratedTokenType Type { get; }");
            WriteLine("string Value { get; }");
            WriteLine("int Line { get; }");
            WriteLine("int Column { get; }");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Generate GeneratedTokenInfo implementing ITokenInfo
            WriteLine("/// <summary>");
            WriteLine("/// CPython 3.12 compatible token info");
            WriteLine("/// </summary>");
            WriteLine("public class GeneratedTokenInfo : ITokenInfo");
            WriteLine("{");
            Indent();

            WriteLine("public GeneratedTokenType Type { get; set; }");
            WriteLine("public string Value { get; set; } = \"\";");
            WriteLine("public int Line { get; set; }");
            WriteLine("public int Column { get; set; }");
            WriteLine("public int Start { get; set; }");
            WriteLine("public int End { get; set; }");
            WriteLine();

            WriteLine("public GeneratedTokenInfo(GeneratedTokenType type, string value, int line, int column, int start = 0, int end = 0)");
            WriteLine("{");
            Indent();
            WriteLine("Type = type;");
            WriteLine("Value = value;");
            WriteLine("Line = line;");
            WriteLine("Column = column;");
            WriteLine("Start = start;");
            WriteLine("End = end;");
            Dedent();
            WriteLine("}");

            Dedent();
            WriteLine("}");
            WriteLine();

            // Generate ContextType and ParserContext for PegInterpreter
            WriteLine("/// <summary>");
            WriteLine("/// Parser context types for tracking parsing state - CPython 3.12 compatible");
            WriteLine("/// </summary>");
            WriteLine("public enum ContextType");
            WriteLine("{");
            Indent();
            WriteLine("Module,");
            WriteLine("Function,");
            WriteLine("Class,");
            WriteLine("Loop,");
            WriteLine("Async,");
            WriteLine("Lambda,");
            WriteLine("Comprehension");
            Dedent();
            WriteLine("}");
            WriteLine();

            WriteLine("/// <summary>");
            WriteLine("/// Parser context information for validation");
            WriteLine("/// </summary>");
            WriteLine("public class ParserContext");
            WriteLine("{");
            Indent();
            WriteLine("public ContextType Type { get; set; }");
            WriteLine("public int NestingLevel { get; set; }");
            WriteLine("public int StartPosition { get; set; }");
            WriteLine("public string? Name { get; set; } // Function/class name for debugging");
            WriteLine();
            WriteLine("public ParserContext(ContextType type, int nestingLevel = 0, int startPosition = 0, string? name = null)");
            WriteLine("{");
            Indent();
            WriteLine("Type = type;");
            WriteLine("NestingLevel = nestingLevel;");
            WriteLine("StartPosition = startPosition;");
            WriteLine("Name = name;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("public override string ToString()");
            WriteLine("{");
            Indent();
            _output.AppendLine($"{new string(' ', _indentLevel * 4)}var name = Name ?? \"anonymous\";");
            _output.AppendLine($"{new string(' ', _indentLevel * 4)}return $\"{{Type}}({{name}}) at level {{NestingLevel}}, pos {{StartPosition}}\";");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine();
        }

        private void GenerateGeneratedTokenizerClass()
        {
            WriteLine("/// <summary>");
            WriteLine("/// Generated tokenizer for Python 3.12 grammar");
            WriteLine("/// </summary>");
            WriteLine("public class GeneratedPyTokenizer");
            WriteLine("{");
            Indent();

            GenerateTokenizerFields();
            GenerateTokenizerConstructor();
            GenerateTokenizerMethods();

            Dedent();
            WriteLine("}");
        }

        private void GenerateTokenizerFields()
        {
            WriteLine("private readonly string _source;");
            WriteLine("private readonly string _filename;");
            WriteLine("private int _position;");
            WriteLine("private int _line = 1;");
            WriteLine("private int _column = 0; // CPython uses 0-based column indexing");
            WriteLine("private readonly List<GeneratedTokenInfo> _tokens = new();");
            WriteLine();
            WriteLine("// INDENT/DEDENT handling");
            WriteLine("private readonly Stack<int> _indentStack = new();");
            WriteLine("private bool _atLineStart = true;");
            WriteLine("private readonly Queue<GeneratedTokenInfo> _pendingTokens = new();");
            WriteLine();
            WriteLine("// Line state tracking for NL vs NEWLINE distinction");
            WriteLine("private bool _currentLineHasRealTokens = false;");
            WriteLine();
            WriteLine("// Parentheses context tracking for correct NL/NEWLINE classification");
            WriteLine("private readonly Stack<char> _parenStack = new();");
            WriteLine("private bool IsInsideParentheses => _parenStack.Count > 0;");
            WriteLine();
            WriteLine("// CPython 3.12: Colon context tracking for compound statement NEWLINE tokens");
            WriteLine("// Rule: colon-followed-by-newline always generates NEWLINE token (not NL)");
            WriteLine("private bool _lastTokenWasColon = false;");
            WriteLine();

            // Generate keyword map for Python 3.12 keywords
            WriteLine("private static readonly Dictionary<string, GeneratedTokenType> Keywords = new()");
            WriteLine("{");
            Indent();

            // Python 3.12 keywords (excluding soft keywords match/case)
            var pythonKeywords = new[]
            {
                "False", "None", "True", "__peg_parser__", "and", "as", "assert", "async", "await",
                "break", "class", "continue", "def", "del", "elif", "else", "except", "finally",
                "for", "from", "global", "if", "import", "in", "is", "lambda", "nonlocal", "not",
                "or", "pass", "raise", "return", "try", "while", "with", "yield"
            };

            foreach (var keyword in pythonKeywords)
            {
                // Map special keywords to their specific token types
                var tokenType = keyword switch
                {
                    // Built-in constants - these are special in CPython 3.12
                    "True" => "GeneratedTokenType.NAME",  // Constants handled as special NAME tokens
                    "False" => "GeneratedTokenType.NAME", // Constants handled as special NAME tokens
                    "None" => "GeneratedTokenType.NAME",  // Constants handled as special NAME tokens
                    // Async/await keywords
                    "async" => "GeneratedTokenType.ASYNC",
                    "await" => "GeneratedTokenType.AWAIT",
                    // All other keywords are standard NAME tokens in CPython 3.12
                    _ => "GeneratedTokenType.NAME"
                };
                WriteLine($"{{ \"{keyword}\", {tokenType} }}, // {keyword}");
            }

            Dedent();
            WriteLine("};");
            WriteLine();

            // Generate operator map
            var operators = _tokens.Where(t => t.IsLiteral).ToList();
            if (operators.Any())
            {
                WriteLine("private static readonly Dictionary<string, GeneratedTokenType> Operators = new()");
                WriteLine("{");
                Indent();

                // Sort by length (longer first) to match properly
                var sortedOperators = operators.OrderByDescending(op => op.Value.Length);
                foreach (var op in sortedOperators)
                {
                    WriteLine($"{{ \"{EscapeString(op.Value)}\", GeneratedTokenType.OP }},");
                }

                Dedent();
                WriteLine("};");
                WriteLine();
            }
        }

        private void GenerateTokenizerConstructor()
        {
            WriteLine("public GeneratedPyTokenizer(string source, string filename = \"<string>\")");
            WriteLine("{");
            Indent();
            WriteLine("_source = source ?? throw new ArgumentNullException(nameof(source));");
            WriteLine("_filename = filename;");
            WriteLine("_position = 0;");
            WriteLine("_indentStack.Push(0); // Initialize with base indentation level");
            Dedent();
            WriteLine("}");
            WriteLine();
        }

        private void GenerateTokenizerMethods()
        {
            GenerateTokenizeMethod();
            GenerateHelperMethods();
        }

        private void GenerateTokenizeMethod()
        {
            WriteLine("/// <summary>");
            WriteLine("/// Tokenize the source code");
            WriteLine("/// </summary>");
            WriteLine("public List<GeneratedTokenInfo> Tokenize()");
            WriteLine("{");
            Indent();

            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine(\"[DEBUG] Tokenize() method started\");");
            WriteLine("#endif");
            WriteLine("_tokens.Clear();");
            WriteLine("_position = 0;");
            WriteLine("_line = 1;");
            WriteLine("_column = 0; // CPython uses 0-based column indexing");
            WriteLine("_currentLineHasRealTokens = false; // Reset line state tracking");
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine($\"[DEBUG] Source length: {_source.Length}, Source: '{_source}'\");");
            WriteLine("#endif");
            WriteLine();

            WriteLine("// Skip ENCODING token for compatibility with CPython generate_tokens()");
            WriteLine("// AddToken(GeneratedTokenType.ENCODING, \"utf-8\", 0, 0);");
            WriteLine();

            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine(\"[DEBUG] Starting main tokenization loop\");");
            WriteLine("#endif");
            WriteLine("while (_position < _source.Length)");
            WriteLine("{");
            Indent();
            WriteLine("var startPosition = _position; // Track position for infinite loop detection");
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine($\"[DEBUG] Loop iteration: position={_position}, char='{CurrentChar}', ASCII={(int)CurrentChar}\");");
            WriteLine("#endif");
            WriteLine();

            WriteLine("// Process indentation at start of line before any other tokens");
            WriteLine("if (_atLineStart)");
            WriteLine("{");
            Indent();
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine(\"[DEBUG] Calling HandleIndentation\");");
            WriteLine("#endif");
            WriteLine("HandleIndentation();");
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine(\"[DEBUG] HandleIndentation completed\");");
            WriteLine("#endif");
            WriteLine("ProcessPendingTokens();");
            Dedent();
            WriteLine("}");
            WriteLine();

            WriteLine("if (char.IsWhiteSpace(CurrentChar) || CurrentChar == '\\r')");
            WriteLine("{");
            Indent();
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine($\"[DEBUG] Calling HandleWhitespace at position {_position}, char='{CurrentChar}', ASCII={(int)CurrentChar}\");");
            WriteLine("#endif");
            WriteLine("HandleWhitespace();");
            Dedent();
            WriteLine("}");
            WriteLine("else if (CurrentChar == '#')");
            WriteLine("{");
            Indent();
            WriteLine("HandleComment();");
            Dedent();
            WriteLine("}");
            WriteLine("else if (IsFStringStart())");
            WriteLine("{");
            Indent();
            WriteLine("HandleFString();");
            Dedent();
            WriteLine("}");
            WriteLine("else if (char.IsLetter(CurrentChar) || CurrentChar == '_')");
            WriteLine("{");
            Indent();
            WriteLine("HandleNameOrKeyword();");
            Dedent();
            WriteLine("}");
            WriteLine("else if (char.IsDigit(CurrentChar))");
            WriteLine("{");
            Indent();
            WriteLine("HandleNumber();");
            Dedent();
            WriteLine("}");
            WriteLine("else if (CurrentChar == '\\\"' || CurrentChar == '\\'')");
            WriteLine("{");
            Indent();
            WriteLine("HandleString();");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("if (!HandleOperator())");
            WriteLine("{");
            Indent();
            WriteLine("AddToken(GeneratedTokenType.ERRORTOKEN, CurrentChar.ToString(), _line, _column);");
            WriteLine("_currentLineHasRealTokens = true; // Mark line as having real tokens");
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// CRITICAL: Infinite loop protection");
            WriteLine("if (_position == startPosition)");
            WriteLine("{");
            Indent();
            WriteLine("Console.WriteLine($\"[ERROR] Tokenizer infinite loop detected at position {_position}, char: '{CurrentChar}'. Forcing advance.\");");
            WriteLine("Advance(); // Force advance to prevent infinite loop");
            Dedent();
            WriteLine("}");

            Dedent();
            WriteLine("}");
            WriteLine();

            WriteLine("// Add final NEWLINE if file doesn't end with newline (BEFORE DEDENT for CPython compatibility)");
            WriteLine("if (_position > 0 && _source[_position - 1] != '\\n' && _source[_position - 1] != '\\r')");
            WriteLine("{");
            Indent();
            WriteLine("AddToken(GeneratedTokenType.NEWLINE, \"\", _line, _column);");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Generate remaining DEDENT tokens at EOF");
            WriteLine("while (_indentStack.Count > 1)");
            WriteLine("{");
            Indent();
            WriteLine("_indentStack.Pop();");
            WriteLine("_pendingTokens.Enqueue(new GeneratedTokenInfo(GeneratedTokenType.DEDENT, \"\", _line + 1, 0));");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Process any pending tokens at EOF");
            WriteLine("ProcessPendingTokens();");
            WriteLine();
            WriteLine("// Add ENDMARKER for compatibility with CPython generate_tokens()");
            WriteLine("AddToken(GeneratedTokenType.ENDMARKER, \"\", _line, _column);");
            WriteLine("return _tokens;");

            Dedent();
            WriteLine("}");
            WriteLine();
        }

        private void GenerateHelperMethods()
        {
            // Current character property
            WriteLine("private char CurrentChar => _position < _source.Length ? _source[_position] : '\\0';");
            WriteLine();

            // Advance method
            WriteLine("private void Advance()");
            WriteLine("{");
            Indent();
            WriteLine("if (_position < _source.Length)");
            WriteLine("{");
            Indent();
            WriteLine("if (_source[_position] == '\\n')");
            WriteLine("{");
            Indent();
            WriteLine("_line++;");
            WriteLine("_column = 0; // CPython uses 0-based column indexing");
            WriteLine("_atLineStart = true; // Next position will be start of new line");
            WriteLine("// NOTE: Do not reset _currentLineHasRealTokens here - it should be reset AFTER we decide NL vs NEWLINE");
            Dedent();
            WriteLine("}");
            WriteLine("else if (_source[_position] == '\\r')");
            WriteLine("{");
            Indent();
            WriteLine("// Handle \\r character for line tracking");
            WriteLine("_line++;");
            WriteLine("_column = 0; // CPython uses 0-based column indexing");
            WriteLine("_atLineStart = true; // Next position will be start of new line");
            WriteLine("// Check if this is followed by \\n (Windows CRLF)");
            WriteLine("if (_position + 1 < _source.Length && _source[_position + 1] == '\\n')");
            WriteLine("{");
            Indent();
            WriteLine("// This is \\r\\n, advance past \\r but don't double-increment line");
            WriteLine("_position++;");
            WriteLine("// The \\n will be processed next and should not increment line again");
            WriteLine("// So we temporarily reset line tracking for the \\n");
            WriteLine("_line--; // Compensate because \\n handler will increment again");
            WriteLine("_atLineStart = false; // Let \\n handler set this");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("// Standalone \\r - advance normally");
            WriteLine("_position++;");
            Dedent();
            WriteLine("}");
            WriteLine("return; // Early return to avoid double increment");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("_column++;");
            Dedent();
            WriteLine("}");
            WriteLine("_position++;");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Add token method
            WriteLine("private void AddToken(GeneratedTokenType type, string value)");
            WriteLine("{");
            Indent();
            WriteLine("_tokens.Add(new GeneratedTokenInfo(type, value, _line, _column));");
            Dedent();
            WriteLine("}");
            WriteLine();

            WriteLine("private void AddToken(GeneratedTokenType type, string value, int startLine, int startColumn)");
            WriteLine("{");
            Indent();
            WriteLine("_tokens.Add(new GeneratedTokenInfo(type, value, startLine, startColumn));");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Handle whitespace
            WriteLine("private void HandleWhitespace()");
            WriteLine("{");
            Indent();
            WriteLine("while (_position < _source.Length && char.IsWhiteSpace(CurrentChar))");
            WriteLine("{");
            Indent();
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine($\"[DEBUG] HandleWhitespace loop: position={_position}, char='{CurrentChar}', ASCII={(int)CurrentChar}\");");
            WriteLine("#endif");
            WriteLine("if (CurrentChar == '\\r')");
            WriteLine("{");
            Indent();
            WriteLine("// Handle \\r character - could be part of \\r\\n sequence");
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine($\"[DEBUG] Found \\r at position {_position}, checking next char...\");");
            WriteLine("#endif");
            WriteLine("// Check if next character is \\n for Windows line ending");
            WriteLine("if (_position + 1 < _source.Length && _source[_position + 1] == '\\n')");
            WriteLine("{");
            Indent();
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine($\"[DEBUG] Found \\r\\n sequence: skipping \\r, will process \\n next\");");
            WriteLine("#endif");
            WriteLine("// This is a \\r\\n sequence, advance past \\r and let \\n handler process it");
            WriteLine("Advance(); // Skip \\r, \\n will be processed in next iteration");
            WriteLine("continue; // Continue loop to process \\n character");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("// Standalone \\r (Mac-style line ending) - treat as newline");
            WriteLine("var newlineColumn = _column;");
            WriteLine("var newlineValue = \"\\r\";");
            WriteLine();
            WriteLine("// CPython 3.12: Colon-followed-by-newline always generates NEWLINE token");
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine($\"[DEBUG] Standalone \\r: checking _lastTokenWasColon: {_lastTokenWasColon}\");");
            WriteLine("#endif");
            WriteLine("if (_lastTokenWasColon)");
            WriteLine("{");
            Indent();
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine($\"[DEBUG] Generating NEWLINE token after colon (standalone \\r): value='{newlineValue}', line={_line}, col={newlineColumn}\");");
            WriteLine("#endif");
            WriteLine("AddToken(GeneratedTokenType.NEWLINE, newlineValue, _line, newlineColumn);");
            WriteLine("_lastTokenWasColon = false; // Reset after processing");
            Dedent();
            WriteLine("}");
            WriteLine("// Inside parentheses: always NL; Outside: check if blank line");
            WriteLine("else if (IsInsideParentheses)");
            WriteLine("{");
            Indent();
            WriteLine("AddToken(GeneratedTokenType.NL, newlineValue, _line, newlineColumn);");
            WriteLine("// Process pending DEDENT tokens after NL");
            WriteLine("ProcessPendingTokens();");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("bool isBlankLine = IsBlankLine();");
            WriteLine("if (isBlankLine)");
            WriteLine("{");
            Indent();
            WriteLine("AddToken(GeneratedTokenType.NL, newlineValue, _line, newlineColumn);");
            WriteLine("// Process pending DEDENT tokens after NL");
            WriteLine("ProcessPendingTokens();");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("AddToken(GeneratedTokenType.NEWLINE, newlineValue, _line, newlineColumn);");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine("_atLineStart = true;");
            WriteLine("// Process pending DEDENT tokens after NEWLINE");
            WriteLine("ProcessPendingTokens();");
            WriteLine("_currentLineHasRealTokens = false; // Reset for new line");
            WriteLine("Advance();");
            WriteLine("// Indentation will be handled at the start of the main loop");
            WriteLine("break; // Stop processing whitespace after handling newline");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine("else if (CurrentChar == '\\n')");
            WriteLine("{");
            Indent();
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine($\"[DEBUG] Found \\n at position {_position}, processing newline...\");");
            WriteLine("#endif");
            WriteLine("// Store newline position before advancing - CPython uses start position");
            WriteLine("var newlineColumn = _column;");
            WriteLine("// Check for \\r\\n sequence (Windows line ending)");
            WriteLine("var newlineValue = \"\\n\";");
            WriteLine("if (_position > 0 && _source[_position - 1] == '\\r')");
            WriteLine("{");
            Indent();
            WriteLine("newlineValue = \"\\r\\n\";");
            WriteLine("newlineColumn = _column - 1; // Start from \\r position");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// CPython 3.12: Colon-followed-by-newline always generates NEWLINE token");
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine($\"[DEBUG] \\n processing: checking _lastTokenWasColon: {_lastTokenWasColon}, newlineValue='{newlineValue}'\");");
            WriteLine("#endif");
            WriteLine("if (_lastTokenWasColon)");
            WriteLine("{");
            Indent();
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine($\"[DEBUG] Generating NEWLINE token after colon (\\n processing): value='{newlineValue}', line={_line}, col={newlineColumn}\");");
            WriteLine("#endif");
            WriteLine("AddToken(GeneratedTokenType.NEWLINE, newlineValue, _line, newlineColumn);");
            WriteLine("_lastTokenWasColon = false; // Reset after processing");
            Dedent();
            WriteLine("}");
            WriteLine("// Inside parentheses: always NL; Outside: check if blank line");
            WriteLine("else if (IsInsideParentheses)");
            WriteLine("{");
            Indent();
            WriteLine("AddToken(GeneratedTokenType.NL, newlineValue, _line, newlineColumn);");
            WriteLine("// Process pending DEDENT tokens after NL");
            WriteLine("ProcessPendingTokens();");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("bool isBlankLine = IsBlankLine();");
            WriteLine("if (isBlankLine)");
            WriteLine("{");
            Indent();
            WriteLine("AddToken(GeneratedTokenType.NL, newlineValue, _line, newlineColumn);");
            WriteLine("// Process pending DEDENT tokens after NL");
            WriteLine("ProcessPendingTokens();");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("AddToken(GeneratedTokenType.NEWLINE, newlineValue, _line, newlineColumn);");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine("_atLineStart = true;");
            WriteLine("// Process pending DEDENT tokens after NEWLINE");
            WriteLine("ProcessPendingTokens();");
            WriteLine("_currentLineHasRealTokens = false; // Reset for new line");
            WriteLine("Advance();");
            WriteLine("// Indentation will be handled at the start of the main loop");
            WriteLine("break; // Stop processing whitespace after handling newline");
            Dedent();
            WriteLine("}");
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine($\"[DEBUG] HandleWhitespace method ended: position={_position}, char='{CurrentChar}', ASCII={(int)CurrentChar}\");");
            WriteLine("#endif");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("private bool IsBlankLine()");
            WriteLine("{");
            Indent();
            WriteLine("// A blank line is one that contains only comments and/or whitespace");
            WriteLine("// CPython rule: if no real tokens on current line, it's blank");
            WriteLine("return !_currentLineHasRealTokens;");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Process pending tokens (mainly for DEDENT ordering)
            WriteLine("private void ProcessPendingTokens()");
            WriteLine("{");
            Indent();
            WriteLine("while (_pendingTokens.Count > 0)");
            WriteLine("{");
            Indent();
            WriteLine("var pending = _pendingTokens.Dequeue();");
            WriteLine("_tokens.Add(pending);");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Handle comment
            WriteLine("private void HandleComment()");
            WriteLine("{");
            Indent();
            WriteLine("var start = _position;");
            WriteLine("var startLine = _line;");
            WriteLine("var startColumn = _column;");
            WriteLine("while (_position < _source.Length && CurrentChar != '\\n')");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine("var comment = _source.Substring(start, _position - start);");
            WriteLine("AddToken(GeneratedTokenType.COMMENT, comment, startLine, startColumn);");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Handle name or keyword - check for string prefixes first
            WriteLine("private void HandleNameOrKeyword()");
            WriteLine("{");
            Indent();
            WriteLine("var start = _position;");
            WriteLine("var startLine = _line;");
            WriteLine("var startColumn = _column;");
            WriteLine();
            WriteLine("// Check for string prefixes first (r, b, rb, br, f, fr, rf)");
            WriteLine("// Also check for numeric string prefixes that might be confused");
            WriteLine("if (IsStringPrefix())");
            WriteLine("{");
            Indent();
            WriteLine("HandleString();");
            WriteLine("return;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("while (_position < _source.Length && (char.IsLetterOrDigit(CurrentChar) || CurrentChar == '_'))");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine("var name = _source.Substring(start, _position - start);");
            WriteLine();
            WriteLine("// Handle soft keywords (match/case are context-sensitive)");
            WriteLine("GeneratedTokenType tokenType;");
            WriteLine("if (Keywords.ContainsKey(name))");
            WriteLine("{");
            Indent();
            WriteLine("tokenType = Keywords[name];");
            Dedent();
            WriteLine("}");
            WriteLine("else if (name == \"match\" || name == \"case\")");
            WriteLine("{");
            Indent();
            WriteLine("// For now, treat match/case as NAME tokens");
            WriteLine("// TODO: Context-sensitive parsing will be handled in parser");
            WriteLine("tokenType = GeneratedTokenType.NAME;");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("tokenType = GeneratedTokenType.NAME;");
            Dedent();
            WriteLine("}");
            WriteLine("AddToken(tokenType, name, startLine, startColumn);");
            WriteLine("_currentLineHasRealTokens = true; // Mark line as having real tokens");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Handle number - comprehensive Python 3.12 number parsing
            WriteLine("private void HandleNumber()");
            WriteLine("{");
            Indent();
            WriteLine("var start = _position;");
            WriteLine("var startLine = _line;");
            WriteLine("var startColumn = _column;");
            WriteLine();
            WriteLine("// Check for special prefixes: 0x, 0X, 0o, 0O, 0b, 0B");
            WriteLine("if (CurrentChar == '0' && _position + 1 < _source.Length)");
            WriteLine("{");
            Indent();
            WriteLine("char nextChar = char.ToLower(_source[_position + 1]);");
            WriteLine("if (nextChar == 'x')");
            WriteLine("{");
            Indent();
            WriteLine("// Hexadecimal number");
            WriteLine("Advance(); // Skip '0'");
            WriteLine("Advance(); // Skip 'x' or 'X'");
            WriteLine("while (_position < _source.Length && (char.IsDigit(CurrentChar) || (char.ToLower(CurrentChar) >= 'a' && char.ToLower(CurrentChar) <= 'f') || CurrentChar == '_'))");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine("else if (nextChar == 'o')");
            WriteLine("{");
            Indent();
            WriteLine("// Octal number");
            WriteLine("Advance(); // Skip '0'");
            WriteLine("Advance(); // Skip 'o' or 'O'");
            WriteLine("while (_position < _source.Length && (CurrentChar >= '0' && CurrentChar <= '7' || CurrentChar == '_'))");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine("else if (nextChar == 'b')");
            WriteLine("{");
            Indent();
            WriteLine("// Binary number");
            WriteLine("Advance(); // Skip '0'");
            WriteLine("Advance(); // Skip 'b' or 'B'");
            WriteLine("while (_position < _source.Length && (CurrentChar == '0' || CurrentChar == '1' || CurrentChar == '_'))");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("// Regular number starting with 0");
            WriteLine("ParseDecimalNumber();");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("// Regular decimal number");
            WriteLine("ParseDecimalNumber();");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Check for complex number suffix (j/J)");
            WriteLine("if (_position < _source.Length && char.ToLower(CurrentChar) == 'j')");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("var number = _source.Substring(start, _position - start);");
            WriteLine("AddToken(GeneratedTokenType.NUMBER, number, startLine, startColumn);");
            WriteLine("_currentLineHasRealTokens = true; // Mark line as having real tokens");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("private void ParseDecimalNumber()");
            WriteLine("{");
            Indent();
            WriteLine("// Parse integer part");
            WriteLine("while (_position < _source.Length && (char.IsDigit(CurrentChar) || CurrentChar == '_'))");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Check for decimal point");
            WriteLine("if (_position < _source.Length && CurrentChar == '.')");
            WriteLine("{");
            Indent();
            WriteLine("Advance(); // Skip '.'");
            WriteLine("// Parse fractional part");
            WriteLine("while (_position < _source.Length && (char.IsDigit(CurrentChar) || CurrentChar == '_'))");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Check for scientific notation (e/E)");
            WriteLine("if (_position < _source.Length && char.ToLower(CurrentChar) == 'e')");
            WriteLine("{");
            Indent();
            WriteLine("Advance(); // Skip 'e' or 'E'");
            WriteLine("// Check for optional sign");
            WriteLine("if (_position < _source.Length && (CurrentChar == '+' || CurrentChar == '-'))");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine("// Parse exponent");
            WriteLine("while (_position < _source.Length && (char.IsDigit(CurrentChar) || CurrentChar == '_'))");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Handle string - with prefix support
            WriteLine("private void HandleString()");
            WriteLine("{");
            Indent();
            WriteLine("var start = _position;");
            WriteLine("var startLine = _line;");
            WriteLine("var startColumn = _column;");
            WriteLine();
            WriteLine("// Skip any string prefix (r, b, rb, br, f, fr, rf)");
            WriteLine("while (_position < _source.Length && char.IsLetter(CurrentChar))");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Now we should be at the quote");
            WriteLine("if (_position >= _source.Length || (CurrentChar != '\\\"' && CurrentChar != '\\''))");
            WriteLine("{");
            Indent();
            WriteLine("// Not a valid string, treat as regular name");
            WriteLine("_position = start; // Reset position");
            WriteLine("while (_position < _source.Length && (char.IsLetterOrDigit(CurrentChar) || CurrentChar == '_'))");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine("var name = _source.Substring(start, _position - start);");
            WriteLine("var tokenType = Keywords.ContainsKey(name) ? Keywords[name] : GeneratedTokenType.NAME;");
            WriteLine("AddToken(tokenType, name, startLine, startColumn);");
            WriteLine("_currentLineHasRealTokens = true; // Mark line as having real tokens");
            WriteLine("return;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("var quote = CurrentChar;");
            WriteLine();
            WriteLine("// Check for triple-quoted strings");
            WriteLine("if (_position + 2 < _source.Length && _source[_position + 1] == quote && _source[_position + 2] == quote)");
            WriteLine("{");
            Indent();
            WriteLine("HandleTripleQuotedString(quote, start, startLine, startColumn);");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("HandleRegularString(quote, start, startLine, startColumn);");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("private void HandleTripleQuotedString(char quote, int start, int startLine, int startColumn)");
            WriteLine("{");
            Indent();
            WriteLine("_position += 3; // Skip opening triple quotes");
            WriteLine();
            WriteLine("// Read until closing triple quotes");
            WriteLine("while (_position + 2 < _source.Length)");
            WriteLine("{");
            Indent();
            WriteLine("if (_source[_position] == quote && _source[_position + 1] == quote && _source[_position + 2] == quote)");
            WriteLine("{");
            Indent();
            WriteLine("_position += 3; // Skip closing triple quotes");
            WriteLine("break;");
            Dedent();
            WriteLine("}");
            WriteLine("Advance(); // This handles line counting for multiline strings");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("var str = _source.Substring(start, _position - start);");
            WriteLine("AddToken(GeneratedTokenType.STRING, str, startLine, startColumn);");
            WriteLine("_currentLineHasRealTokens = true; // Mark line as having real tokens");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("private void HandleRegularString(char quote, int start, int startLine, int startColumn)");
            WriteLine("{");
            Indent();
            WriteLine("Advance(); // Skip opening quote");
            WriteLine();
            WriteLine("while (_position < _source.Length && CurrentChar != quote)");
            WriteLine("{");
            Indent();
            WriteLine("if (CurrentChar == '\\\\' && _position + 1 < _source.Length)");
            WriteLine("{");
            Indent();
            WriteLine("Advance(); // Skip escape character");
            Dedent();
            WriteLine("}");
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("if (_position < _source.Length)");
            WriteLine("{");
            Indent();
            WriteLine("Advance(); // Skip closing quote");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("var str = _source.Substring(start, _position - start);");
            WriteLine("AddToken(GeneratedTokenType.STRING, str, startLine, startColumn);");
            WriteLine("_currentLineHasRealTokens = true; // Mark line as having real tokens");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("private bool IsFStringStart()");
            WriteLine("{");
            Indent();
            WriteLine("// Check for f\"...\" or f'...' or F\"...\" or F'...'");
            WriteLine("if ((CurrentChar == 'f' || CurrentChar == 'F') && _position + 1 < _source.Length)");
            WriteLine("{");
            Indent();
            WriteLine("char nextChar = _source[_position + 1];");
            WriteLine("if (nextChar == '\\\"' || nextChar == '\\'')");
            WriteLine("{");
            Indent();
            WriteLine("return true;");
            Dedent();
            WriteLine("}");
            WriteLine("// Check for rf\"...\" or rf'...' or fr\"...\" or fr'...'");
            WriteLine("if ((nextChar == 'r' || nextChar == 'R') && _position + 2 < _source.Length)");
            WriteLine("{");
            Indent();
            WriteLine("char thirdChar = _source[_position + 2];");
            WriteLine("if (thirdChar == '\\\"' || thirdChar == '\\'')");
            WriteLine("{");
            Indent();
            WriteLine("return true;");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine("// Check for triple-quoted f-strings: f\"\"\" or f'''");
            WriteLine("if (_position + 3 < _source.Length && nextChar == '\\\"' && _source[_position + 2] == '\\\"' && _source[_position + 3] == '\\\"')");
            WriteLine("{");
            Indent();
            WriteLine("return true;");
            Dedent();
            WriteLine("}");
            WriteLine("if (_position + 3 < _source.Length && nextChar == '\\'' && _source[_position + 2] == '\\'' && _source[_position + 3] == '\\'')");
            WriteLine("{");
            Indent();
            WriteLine("return true;");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine("// Check for r\"...\" or r'...' or R\"...\" or R'...' that might be part of rf/fr");
            WriteLine("if ((CurrentChar == 'r' || CurrentChar == 'R') && _position + 1 < _source.Length)");
            WriteLine("{");
            Indent();
            WriteLine("char nextChar = _source[_position + 1];");
            WriteLine("if ((nextChar == 'f' || nextChar == 'F') && _position + 2 < _source.Length)");
            WriteLine("{");
            Indent();
            WriteLine("char thirdChar = _source[_position + 2];");
            WriteLine("if (thirdChar == '\\\"' || thirdChar == '\\'')");
            WriteLine("{");
            Indent();
            WriteLine("return true;");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine("return false;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("private void HandleFString()");
            WriteLine("{");
            Indent();
            WriteLine("var startLine = _line;");
            WriteLine("var startColumn = _column;");
            WriteLine();
            WriteLine("// Determine prefix (f, rf, fr)");
            WriteLine("string prefix = \"\";");
            WriteLine("if (CurrentChar == 'f' || CurrentChar == 'F')");
            WriteLine("{");
            Indent();
            WriteLine("prefix += CurrentChar;");
            WriteLine("Advance(); // Skip 'f' or 'F'");
            WriteLine("// Check for 'r' after 'f'");
            WriteLine("if (CurrentChar == 'r' || CurrentChar == 'R')");
            WriteLine("{");
            Indent();
            WriteLine("prefix += CurrentChar;");
            WriteLine("Advance(); // Skip 'r' or 'R'");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine("else if (CurrentChar == 'r' || CurrentChar == 'R')");
            WriteLine("{");
            Indent();
            WriteLine("prefix += CurrentChar;");
            WriteLine("Advance(); // Skip 'r' or 'R'");
            WriteLine("// Must have 'f' after 'r'");
            WriteLine("if (CurrentChar == 'f' || CurrentChar == 'F')");
            WriteLine("{");
            Indent();
            WriteLine("prefix += CurrentChar;");
            WriteLine("Advance(); // Skip 'f' or 'F'");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("var quote = CurrentChar;");
            WriteLine("bool isTripleQuoted = false;");
            WriteLine();
            WriteLine("// Check for triple quotes");
            WriteLine("if (_position + 2 < _source.Length && _source[_position + 1] == quote && _source[_position + 2] == quote)");
            WriteLine("{");
            Indent();
            WriteLine("isTripleQuoted = true;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Generate FSTRING_START token (f\", rf\", fr\", etc.)");
            WriteLine("string startToken;");
            WriteLine("if (isTripleQuoted)");
            WriteLine("{");
            Indent();
            WriteLine("startToken = $\"{prefix}{new string(quote, 3)}\";");
            WriteLine("_position += 3; // Skip opening triple quotes");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("startToken = $\"{prefix}{quote}\";");
            WriteLine("_position += 1; // Skip opening quote");
            Dedent();
            WriteLine("}");
            WriteLine("AddToken(GeneratedTokenType.FSTRING_START, startToken, startLine, startColumn);");
            WriteLine("_currentLineHasRealTokens = true; // Mark line as having real tokens");
            WriteLine();
            WriteLine("// Parse f-string content with expression handling");
            WriteLine("ParseFStringContent(quote, isTripleQuoted);");
            WriteLine();
            WriteLine("// Generate FSTRING_END token");
            WriteLine("string endToken = isTripleQuoted ? new string(quote, 3) : quote.ToString();");
            WriteLine("AddToken(GeneratedTokenType.FSTRING_END, endToken, _line, _column);");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("private void ParseFStringContent(char quote, bool isTripleQuoted)");
            WriteLine("{");
            Indent();
            WriteLine("var content = new System.Text.StringBuilder();");
            WriteLine();
            WriteLine("while (_position < _source.Length)");
            WriteLine("{");
            Indent();
            WriteLine("// Check for end of f-string");
            WriteLine("if (isTripleQuoted)");
            WriteLine("{");
            Indent();
            WriteLine("if (_position + 2 < _source.Length && _source[_position] == quote && _source[_position + 1] == quote && _source[_position + 2] == quote)");
            WriteLine("{");
            Indent();
            WriteLine("_position += 3; // Skip closing triple quotes");
            WriteLine("break;");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("if (CurrentChar == quote)");
            WriteLine("{");
            Indent();
            WriteLine("_position += 1; // Skip closing quote");
            WriteLine("break;");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Handle escape sequences");
            WriteLine("if (CurrentChar == '\\\\' && _position + 1 < _source.Length)");
            WriteLine("{");
            Indent();
            WriteLine("content.Append(CurrentChar);");
            WriteLine("Advance();");
            WriteLine("content.Append(CurrentChar);");
            WriteLine("Advance();");
            WriteLine("continue;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Handle opening brace - emit as separate OP token like CPython");
            WriteLine("if (CurrentChar == '{')");
            WriteLine("{");
            Indent();
            WriteLine("// First emit any accumulated text content");
            WriteLine("if (content.Length > 0)");
            WriteLine("{");
            Indent();
            WriteLine("AddToken(GeneratedTokenType.FSTRING_MIDDLE, content.ToString(), _line, _column);");
            WriteLine("_currentLineHasRealTokens = true; // Mark line as having real tokens");
            WriteLine("content.Clear();");
            Dedent();
            WriteLine("}");
            WriteLine("// Emit opening brace as OP token");
            WriteLine("AddToken(GeneratedTokenType.OP, \"{\", _line, _column);");
            WriteLine("_currentLineHasRealTokens = true; // Mark line as having real tokens");
            WriteLine("Advance();");
            WriteLine();
            WriteLine("// Parse expression inside braces with full tokenization like CPython");
            WriteLine("ParseFStringExpression();");
            Dedent();
            WriteLine("}");
            WriteLine("// Handle closing brace - emit as separate OP token like CPython");
            WriteLine("else if (CurrentChar == '}')");
            WriteLine("{");
            Indent();
            WriteLine("// This should not be reached as ParseFStringExpression handles the closing brace");
            WriteLine("AddToken(GeneratedTokenType.OP, \"}\", _line, _column);");
            WriteLine("_currentLineHasRealTokens = true; // Mark line as having real tokens");
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("content.Append(CurrentChar);");
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Emit any remaining content");
            WriteLine("if (content.Length > 0)");
            WriteLine("{");
            Indent();
            WriteLine("AddToken(GeneratedTokenType.FSTRING_MIDDLE, content.ToString(), _line, _column);");
            WriteLine("_currentLineHasRealTokens = true; // Mark line as having real tokens");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("private void ParseFStringExpression()");
            WriteLine("{");
            Indent();
            WriteLine("// Parse the expression inside f-string braces with full tokenization like CPython");
            WriteLine("while (_position < _source.Length && CurrentChar != '}')");
            WriteLine("{");
            Indent();
            WriteLine("// Skip whitespace");
            WriteLine("if (char.IsWhiteSpace(CurrentChar))");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            WriteLine("continue;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Handle colon for format specification - switch to FSTRING_MIDDLE mode");
            WriteLine("if (CurrentChar == ':')");
            WriteLine("{");
            Indent();
            WriteLine("// Emit colon as OP token");
            WriteLine("AddToken(GeneratedTokenType.OP, \":\", _line, _column);");
            WriteLine("_currentLineHasRealTokens = true;");
            WriteLine("Advance();");
            WriteLine();
            WriteLine("// Parse format specification as FSTRING_MIDDLE");
            WriteLine("var formatSpec = new System.Text.StringBuilder();");
            WriteLine("while (_position < _source.Length && CurrentChar != '}')");
            WriteLine("{");
            Indent();
            WriteLine("formatSpec.Append(CurrentChar);");
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Emit format spec as FSTRING_MIDDLE token if we have content");
            WriteLine("if (formatSpec.Length > 0)");
            WriteLine("{");
            Indent();
            WriteLine("AddToken(GeneratedTokenType.FSTRING_MIDDLE, formatSpec.ToString(), _line, _column);");
            WriteLine("_currentLineHasRealTokens = true;");
            Dedent();
            WriteLine("}");
            WriteLine("break; // Exit the main loop");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Handle numbers");
            WriteLine("if (char.IsDigit(CurrentChar))");
            WriteLine("{");
            Indent();
            WriteLine("var start = _position;");
            WriteLine("var startLine = _line;");
            WriteLine("var startColumn = _column;");
            WriteLine("while (_position < _source.Length && (char.IsDigit(CurrentChar) || CurrentChar == '.'))");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine("var number = _source.Substring(start, _position - start);");
            WriteLine("AddToken(GeneratedTokenType.NUMBER, number, startLine, startColumn);");
            WriteLine("_currentLineHasRealTokens = true;");
            Dedent();
            WriteLine("}");
            WriteLine("// Handle identifiers and keywords");
            WriteLine("else if (char.IsLetter(CurrentChar) || CurrentChar == '_')");
            WriteLine("{");
            Indent();
            WriteLine("var start = _position;");
            WriteLine("var startLine = _line;");
            WriteLine("var startColumn = _column;");
            WriteLine("while (_position < _source.Length && (char.IsLetterOrDigit(CurrentChar) || CurrentChar == '_'))");
            WriteLine("{");
            Indent();
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine("var name = _source.Substring(start, _position - start);");
            WriteLine();
            WriteLine("// Check if this is a nested f-string start (f followed by quote)");
            WriteLine("if (name == \"f\" && _position < _source.Length && (_source[_position] == '\"' || _source[_position] == '\\''))");
            WriteLine("{");
            Indent();
            WriteLine("// This is a nested f-string, handle it as a complete f-string");
            WriteLine("_position = start; // Reset position to the 'f'");
            WriteLine("HandleFString(); // Recursively handle nested f-string");
            Dedent();
            WriteLine("}");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("// Regular identifier or keyword");
            WriteLine("var tokenType = Keywords.ContainsKey(name) ? Keywords[name] : GeneratedTokenType.NAME;");
            WriteLine("AddToken(tokenType, name, startLine, startColumn);");
            WriteLine("_currentLineHasRealTokens = true;");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine("// Handle operators and punctuation");
            WriteLine("else");
            WriteLine("{");
            Indent();
            WriteLine("var op = CurrentChar.ToString();");
            WriteLine("// Check for multi-character operators");
            WriteLine("if (_position + 1 < _source.Length)");
            WriteLine("{");
            Indent();
            WriteLine("var twoChar = op + _source[_position + 1];");
            WriteLine("if (Operators.ContainsKey(twoChar))");
            WriteLine("{");
            Indent();
            WriteLine("AddToken(GeneratedTokenType.OP, twoChar, _line, _column);");
            WriteLine("_currentLineHasRealTokens = true;");
            WriteLine("Advance();");
            WriteLine("Advance();");
            WriteLine("continue;");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine("// Single character operator");
            WriteLine("AddToken(GeneratedTokenType.OP, op, _line, _column);");
            WriteLine("_currentLineHasRealTokens = true;");
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Emit closing brace as OP token");
            WriteLine("if (CurrentChar == '}')");
            WriteLine("{");
            Indent();
            WriteLine("AddToken(GeneratedTokenType.OP, \"}\", _line, _column);");
            WriteLine("_currentLineHasRealTokens = true;");
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Handle operator
            WriteLine("private bool HandleOperator()");
            WriteLine("{");
            Indent();
            WriteLine("var startLine = _line;");
            WriteLine("var startColumn = _column;");
            WriteLine("// Try to match operators from longest to shortest");
            WriteLine("foreach (var (op, tokenType) in Operators.OrderByDescending(x => x.Key.Length))");
            WriteLine("{");
            Indent();
            WriteLine("if (_position + op.Length <= _source.Length && _source.Substring(_position, op.Length) == op)");
            WriteLine("{");
            Indent();
            WriteLine("AddToken(tokenType, op, startLine, startColumn);");
            WriteLine("_currentLineHasRealTokens = true; // Mark line as having real tokens");
            WriteLine("// Track parentheses context for correct NL/NEWLINE classification");
            WriteLine("if (op == \"(\" || op == \"[\" || op == \"{\")");
            WriteLine("{");
            Indent();
            WriteLine("_parenStack.Push(op[0]);");
            Dedent();
            WriteLine("}");
            WriteLine("else if (op == \")\" || op == \"]\" || op == \"}\")");
            WriteLine("{");
            Indent();
            WriteLine("if (_parenStack.Count > 0) _parenStack.Pop();");
            Dedent();
            WriteLine("}");
            WriteLine("// CPython 3.12: Track colon tokens for compound statement NEWLINE generation");
            WriteLine("if (op == \":\")");
            WriteLine("{");
            Indent();
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine($\"[DEBUG] Colon token detected: setting _lastTokenWasColon = true\");");
            WriteLine("#endif");
            WriteLine("_lastTokenWasColon = true;");
            Dedent();
            WriteLine("}");
            WriteLine("// Reset colon context for non-colon operators");
            WriteLine("else if (op != \":\")");
            WriteLine("{");
            Indent();
            WriteLine("_lastTokenWasColon = false;");
            Dedent();
            WriteLine("}");
            WriteLine("for (int i = 0; i < op.Length; i++) Advance();");
            WriteLine("return true;");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine("return false;");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Handle indentation for INDENT/DEDENT tokens
            WriteLine("private void HandleIndentation()");
            WriteLine("{");
            Indent();
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine($\"[DEBUG] HandleIndentation: _atLineStart={_atLineStart}, position={_position}\");");
            WriteLine("#endif");
            WriteLine("if (!_atLineStart) return;");
            WriteLine("// Skip indentation processing inside parentheses");
            WriteLine("if (IsInsideParentheses)");
            WriteLine("{");
            Indent();
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine(\"[DEBUG] Inside parentheses, setting _atLineStart=false\");");
            WriteLine("#endif");
            WriteLine("_atLineStart = false; // CRITICAL: Must set this to avoid infinite loop");
            WriteLine("return;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Calculate current line indentation");
            WriteLine("int indent = 0;");
            WriteLine("int indentStartColumn = _column; // Save start position for INDENT token");
            WriteLine("while (_position < _source.Length && (CurrentChar == ' ' || CurrentChar == '\\t'))");
            WriteLine("{");
            Indent();
            WriteLine("indent += (CurrentChar == '\\t' ? 8 : 1);");
            WriteLine("Advance();");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// CPython 3.12: Handle empty lines and comments for indentation");
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine($\"[DEBUG] Checking empty line: position={_position}, length={_source.Length}, char='{CurrentChar}'\");");
            WriteLine("#endif");
            WriteLine("if (_position >= _source.Length || CurrentChar == '\\n' || CurrentChar == '#')");
            WriteLine("{");
            Indent();
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine(\"[DEBUG] Empty line detected, setting _atLineStart=false\");");
            WriteLine("#endif");
            WriteLine("_atLineStart = false; // CRITICAL: Must set this to avoid infinite loop");
            WriteLine("// CPython 3.12: Don't process indentation for empty/comment lines");
            WriteLine("// DEDENT tokens will be generated when we encounter the next non-empty line");
            WriteLine("return;");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Handle indentation changes");
            WriteLine("int currentLevel = _indentStack.Peek();");
            WriteLine("if (indent > currentLevel)");
            WriteLine("{");
            Indent();
            WriteLine("// Increased indentation - INDENT");
            WriteLine("// CPython 3.12: Only generate INDENT if we're actually increasing indentation");
            WriteLine("_indentStack.Push(indent);");
            WriteLine("var indentText = new string(' ', indent);");
            WriteLine("AddToken(GeneratedTokenType.INDENT, indentText, _line, indentStartColumn);");
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine($\"[DEBUG] Generated INDENT token: level {currentLevel} -> {indent}\");");
            WriteLine("#endif");
            Dedent();
            WriteLine("}");
            WriteLine("else if (indent < currentLevel)");
            WriteLine("{");
            Indent();
            WriteLine("// Decreased indentation - DEDENT(s)");
            WriteLine("while (_indentStack.Count > 1 && _indentStack.Peek() > indent)");
            WriteLine("{");
            Indent();
            WriteLine("_indentStack.Pop();");
            WriteLine("// CPython 3.12: DEDENT position should point to current indentation level");
            WriteLine("// Use current position (start of current token) not previous position");
            WriteLine("_pendingTokens.Enqueue(new GeneratedTokenInfo(GeneratedTokenType.DEDENT, \"\", _line, indent));");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("// Check for indentation error");
            WriteLine("if (_indentStack.Count > 0 && _indentStack.Peek() != indent)");
            WriteLine("{");
            Indent();
            WriteLine("throw new InvalidOperationException($\"IndentationError: unindent does not match any outer indentation level at line {_line}\");");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine();
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine(\"[DEBUG] Setting _atLineStart=false at end of HandleIndentation\");");
            WriteLine("#endif");
            WriteLine("_atLineStart = false;");
            WriteLine("// Now that we're starting to process this line, reset the line state for real token tracking");
            WriteLine("_currentLineHasRealTokens = false;");
            WriteLine("#if DEBUG_LOG");
            WriteLine("Console.WriteLine(\"[DEBUG] HandleIndentation method ending normally\");");
            WriteLine("#endif");
            Dedent();
            WriteLine("}");
            WriteLine();

            // Add IsStringPrefix method
            WriteLine("private bool IsStringPrefix()");
            WriteLine("{");
            Indent();
            WriteLine("// Check for string prefixes: r, b, rb, br, f, fr, rf");
            WriteLine("if (_position < _source.Length)");
            WriteLine("{");
            Indent();
            WriteLine("char c = char.ToLower(CurrentChar);");
            WriteLine("if (c == 'r' || c == 'b' || c == 'f')");
            WriteLine("{");
            Indent();
            WriteLine("// Check if followed by quote or another prefix");
            WriteLine("if (_position + 1 < _source.Length)");
            WriteLine("{");
            Indent();
            WriteLine("char next = _source[_position + 1];");
            WriteLine("if (next == '\\\"' || next == '\\'')");
            WriteLine("{");
            Indent();
            WriteLine("return true; // Single prefix like r\", b\", f\"");
            Dedent();
            WriteLine("}");
            WriteLine("else if (_position + 2 < _source.Length)");
            WriteLine("{");
            Indent();
            WriteLine("char next2 = char.ToLower(_source[_position + 1]);");
            WriteLine("char next3 = _source[_position + 2];");
            WriteLine("if ((c == 'r' && next2 == 'b') || (c == 'b' && next2 == 'r') || (c == 'f' && next2 == 'r') || (c == 'r' && next2 == 'f'))");
            WriteLine("{");
            Indent();
            WriteLine("if (next3 == '\\\"' || next3 == '\\'')");
            WriteLine("{");
            Indent();
            WriteLine("return true; // Double prefix like rb\", br\", fr\", rf\"");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            Dedent();
            WriteLine("}");
            WriteLine("return false;");
            Dedent();
            WriteLine("}");
        }

        private string EscapeString(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r").Replace("\t", "\\t");
        }

        // Output helper methods
        private void WriteLine(string line = "")
        {
            if (!string.IsNullOrEmpty(line))
            {
                _output.Append(new string(' ', _indentLevel * 4));
                _output.AppendLine(line);
            }
            else
            {
                _output.AppendLine();
            }
        }

        private void Indent() => _indentLevel++;
        private void Dedent() => _indentLevel--;
    }
}